"""
Opus post-hoc atomic decomposition + per-atom verification
(MCAL_PLAN 3.4, build item #6).

Scope is `settings.ATOMIC_VERIFY_FIELDS`: the five `summary.*` subfields plus
`summary_of_interest`. `summary.overview` is deliberately excluded -- it is a
roll-up whose evidence is carried forward from the five subfields (m2.py:321-336),
so decomposing it would double-count the same atoms.

The pipeline is: prose -> Opus decomposition into atoms -> per-atom
`quote_check.check_quote` against `page +/- 2` -> type-specific checks ->
weighted aggregation into a subfield score. One Opus call per subfield. Opus
judging Opus is deliberate (MCAL_PLAN 3.4): JudgeBench's Sonnet-ceiling warning
applies to weak-judge/strong-writer pairings, and there is no ceiling gap here.

The decomposition prompt is HAND-WRITTEN and NOT tuned on the calibration set.
Tuning it on the same nine documents that fit tau would leak calibration data
into the verifier and void the conformal guarantee (MCAL_PLAN 3.4, 7.5). The
false-negative log exists so the prompt can be improved from *qualitative*
patterns -- missing coreference, missing negation -- never from chasing the
graded-set score.

--------------------------------------------------------------------------
Documented deviation: the plan's stated mechanism does not fit its own evidence
--------------------------------------------------------------------------

MCAL_PLAN 1(3) and 1(4) both attribute their failures to "numeric
hallucination" produced by map-reduce decoupling of `(alternative_label <->
figure)`, and both prescribe the same cure: atomic decomposition plus substring
verification. Checked against the documents, that diagnosis is wrong for both
cases. Reproducible via `tests/test_env_impact_magnitude_75_vs_70.py`.

  * LA Transit `$659 million (Alt. V)` (MCAL_PLAN 1(3)). The figure is on
    pp. 31 / 214 / 215 and is correctly paired with Alternative V -- p. 215
    reads "TOTALS - Alternate #5 ... $659.0 M". Nothing is decoupled. What the
    document adds, on p. 283, is the restriction: "For the Rail/Bus Alternatives
    I-V, the capital costs in 1977 dollars range from 659 million and 1.120
    billion dollars." The summary reported the range without that clause, so a
    true statement about five of eleven alternatives became a false statement
    about all eleven. The corpus minimum is $369 million (Alt. XI), on the same
    table the summary cited.

  * LA Transit `Magnitude 7.5` (MCAL_PLAN 1(4)). p. 146 reads verbatim: "The
    most severe ground shaking that would be felt in the starter line area would
    be generated by a Magnitude 7.5 earthquake occurring on the
    Newport-Inglewood Fault". The figure is present, correctly attached to the
    named fault, and 7.5 also appears in the Figure IV.4 fault table on p. 144.
    The human's 7.0 comes from p. 145, which frames 7.0 as the *maximum
    credible* event for that fault. The document states both figures under
    different framings; the summary carried "maximum credible" across a
    coordination ("San Andreas (Magnitude 8.5 maximum credible) and
    Newport-Inglewood (Magnitude 7.5)") and thereby mislabeled which framing 7.5
    belongs to.

Both claims are SUBSTRING-TRUE. No substring verifier -- not this one, not any
-- can reject them, because the text is there. Only one of the three failures
MCAL_PLAN 1(4) lists is a genuine fabrication and therefore genuinely catchable:
the Lincoln Hwy clause "or important wildlife habitats are affected", which
scores content-token coverage 0.00 against its own cited pages and is caught by
coordination splitting. See `tests/test_lincoln_hwy_wildlife_clause.py`.

So this module adds a `scope_qualifier` field to the atom schema and a
qualifier check, on top of the plan's schema:

  1. An atom that is a range endpoint, a superlative, or a comparison MUST carry
     the document's restricting phrase in `scope_qualifier`. An empty qualifier
     on such an atom is a failure -- `T19_scope_qualifier_dropped`.
  2. The qualifier must itself verify against `page +/- 2`. A qualifier the
     verifier cannot locate is not evidence of scope; it is a second unverified
     claim.
  3. A qualifier present in the located source sentence but absent from the
     atom's own text is a dropped qualifier -- also `T19`.

Rule 1 is what catches the cost case: "capital costs range from $659 million to
$1,450 million" is a range endpoint, so it needs a qualifier, and the only
qualifier the document offers ("For the Rail/Bus Alternatives I-V") is on p. 283
and does not verify against the cited p. 214 window. Either way the atom fails.
Rule 3 is what catches the magnitude case: the p. 146 sentence carries "most
severe ... in the starter line area" and the summary's atom does not.

`T19_scope_qualifier_dropped` already exists in `taxonomy.py` as an
empirically-proposed code (`PROPOSED_TAXONOMY`), so this module does not need a
taxonomy amendment -- only human ratification of T19 at v1.

What the qualifier check still CANNOT do, stated plainly so it does not get
mistaken for a solved problem: it cannot adjudicate between 7.0 and 7.5. The
document contains both. `competing_values` is recorded as an advisory diagnostic
for exactly that reason -- it surfaces the contradiction for a human without
pretending to resolve it, and it is not gating because on OCR'd cost tables the
count of "competing" figures is large and mostly spurious.

--------------------------------------------------------------------------
Why s_citation is the signal that matters here
--------------------------------------------------------------------------

T01_missing_citation is the single most common observed failure -- 10 of the 30
wrong items in the Evaluation sheet, and 4/8 docs on
`summary.public_response` alone. It is currently INVISIBLE to the confidence
composite: `s_quote` is the mean over the evidence entries that exist
(`quote_check.s_quote_for`), so a subfield that cites three pages well and
silently omits citations for four more claims scores the same as one that cites
everything. Averaging over present evidence cannot see absent evidence.

Atom-level citation coverage is the only signal that separates them, because
decomposition enumerates the claims rather than the citations. Measured on the 8
graded docs' 40 summary subfields (`tests/test_atomic_verify.py::TestT01Invisibility`):

    graded "ok, missing citation - pg ..."   n=10   mean s_quote = 0.960
    graded clean "ok"                        n=27   mean s_quote = 0.988

A 0.028 gap. There is no threshold on `s_quote` that separates those populations,
because every citation the extractor DID make verifies -- the defect is a claim it
made without one. Worse, the obvious field-level proxy points the wrong way:
evidence-entries-per-sentence is 2.50 on the missing-citation subfields and 2.10
on the clean ones, so a naive "did it cite enough?" heuristic would rank the
defective subfields as better documented.

`s_citation` (fraction of atoms carrying a page cite) is therefore computed here
and exposed in a shape `confidence.compute_signals(citation_rate=...)` accepts
directly. It carries weight 0 today (MCAL_PLAN 3.3 freezes weights at 0.5/0.5
through v3) but is logged from v1 so weight validation has data when n reaches
~60 -- a signal never recorded cannot be retro-fitted.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field as dc_field
from pathlib import Path
from typing import Callable, Optional, Sequence

from . import quote_check as qc
from . import settings

# segment_a bridge is installed by the settings import.
from pages import Doc  # noqa: E402

log = logging.getLogger(__name__)


# --- Vocabulary (MCAL_PLAN 3.4) ---------------------------------------------

CLAIM_TYPES = ("prose", "numeric", "comparative", "categorical", "temporal", "geospatial")
POLARITIES = ("affirmative", "negative")

DEFAULT_CLAIM_TYPE = "prose"
DEFAULT_POLARITY = "affirmative"

# Claim types whose failures carry the 2x aggregation penalty (MCAL_PLAN 3.4).
PENALIZED_CLAIM_TYPES = frozenset({"numeric", "geospatial"})
PENALTY_WEIGHT = 2.0

# The negation cues MCAL_PLAN 3.4 enumerates. This list is exact and closed:
# the plan makes "evidence_quote must contain the negation cue verbatim" a hard
# schema rule, so widening the set here would start rejecting atoms for cues the
# prompt never told the model about.
NEGATION_CUES = (
    "not",
    "no",
    "neither",
    "never",
    "without",
    "except",
    "unless",
    "fails to",
    "does not",
    "would not",
)

# Cues that are unmistakably negative but are NOT in the plan's list. Used only
# to *detect* a probable polarity mislabel and warn; never to fail an atom, since
# the prompt does not ask for them.
EXTRA_NEGATION_CUES = ("nor", "cannot", "none of", "no longer", "absent", "lacks")

# Coordinating conjunctions that must trigger a split (MCAL_PLAN 3.4).
COORDINATORS = ("or", "and", "as well as", "along with")

# Pronouns the plan requires be resolved before verification runs.
PRONOUNS = ("it", "they", "this", "that", "these", "those")

# Generic anaphora from the plan, plus the near-identical forms that appear in
# this corpus's summaries. Matched as whole phrases.
#
# Deliberately EXCLUDES self-referential phrases for the document itself ("the
# document", "the statement", "this EIS"). Their antecedent is the document, not a
# prior mention, so "resolving" them means substituting a title -- and a title is
# usually NOT on the cited page, so the substitution would make the atom harder to
# verify rather than easier. That is the opposite of what MCAL_PLAN 3.4's
# coreference rule is for.
GENERIC_ANAPHORA = (
    "the agency",
    "the agencies",
    "the project",
    "the alternative",
    "the alternatives",
    "the proposed action",
    "the applicant",
    "the department",
    "the bureau",
    "the administration",
)


# --- Template loading -------------------------------------------------------

TEMPLATE_PATH = settings.TEMPLATES_DIR / "atomic_decomposition.md"
_BODY_SEPARATOR = "\n---\n"

# MCAL_PLAN 3.4 requires these rules verbatim in the template. Asserted on load
# so an edit that drops one fails at build time instead of silently shipping a
# decomposer that no longer splits coordinations.
REQUIRED_RULE_FRAGMENTS = (
    "Split this passage into minimal factual claims. One subject-predicate-object per claim.",
    "Coreference resolution",
    "coreference_resolved=false",
    "Negation preservation",
    "polarity=negative",
    "Coordination splitting",
    "Numeric values are separate claims",
    "scope_qualifier",
)


class TemplateError(RuntimeError):
    pass


def load_prompt_template(path: Optional[Path] = None) -> str:
    """
    Model-facing body of `templates/atomic_decomposition.md`.

    Same convention as `templates/m2_plain_language.md` and
    `templates/critic_header.md`: a human-facing provenance header, then a
    `\\n---\\n` rule, then the text the model sees.
    """
    p = path or TEMPLATE_PATH
    if not p.exists():
        raise TemplateError(
            f"Missing atomic decomposition template: {p}. MCAL_PLAN 3.4 requires "
            f"the decomposition rules to live in this file verbatim."
        )
    text = p.read_text(encoding="utf-8")
    _, sep, body = text.partition(_BODY_SEPARATOR)
    body = (body if sep else text).strip()
    missing = [f for f in REQUIRED_RULE_FRAGMENTS if f not in body]
    if missing:
        raise TemplateError(
            f"{p.name} is missing mandatory rule text {missing}. MCAL_PLAN 3.4 "
            f"specifies these rules verbatim; the verifier's behaviour depends on "
            f"the decomposer having been told them."
        )
    return body


# --- Sentence segmentation --------------------------------------------------
# OCR'd EIS pages are not clean prose: tables arrive as newline-separated cell
# runs and headings have no terminal punctuation. So we split on sentence
# punctuation AND on blank-line/newline runs, then keep fragments long enough to
# be worth scoring. Over-splitting is safe here (we only use sentences to
# localize a search); under-splitting is not, because a 3,900-character page
# would then be treated as one context and every qualifier on it would look
# adjacent to every figure.

_SENT_SPLIT = re.compile(r"(?<=[.!?:;])\s+|\n{1,}")
_MIN_SENTENCE_CHARS = 12


def sentences(text: str) -> list[str]:
    """Split OCR text into scoreable fragments. Heuristic, deliberately coarse."""
    if not text:
        return []
    out = []
    for frag in _SENT_SPLIT.split(text):
        s = " ".join((frag or "").split())
        if len(s) >= _MIN_SENTENCE_CHARS:
            out.append(s)
    return out


# --- Deterministic validator: coreference -----------------------------------
# MCAL_PLAN 3.4 makes `coreference_resolved` a model-supplied boolean. Trusting
# it alone is not enough -- a model that forgets the rule reports `true` and the
# unresolved pronoun sails through. So we re-derive it from the atom text.
#
# The hard part is that three of the plan's six pronouns are also determiners.
# "that would displace 78 structures" is a relative clause, and "this Draft EIS"
# is a determiner + noun; neither is unresolved anaphora. Flagging them would
# make the validator fire on almost every atom and be switched off. So:
#
#   * `it` / `they` are flagged whenever they appear as words, EXCEPT for
#     expletive `it` ("it is expected that ..."), which has no antecedent to
#     resolve by construction.
#   * `this` / `that` / `these` / `those` are flagged only in PRONOMINAL
#     position -- followed by a finite verb / auxiliary, or by clause-final
#     punctuation. Followed by a noun they are determiners and fine.
#   * a generic anaphor is NOT flagged when its own antecedent is present in the
#     same text ("The Department of Natural Resources found ... the department"
#     is self-resolving; "The project would include a 318-acre reservoir" is not).
#
# Measured over the 165 sentences of the 8 graded docs' five summary subfields:
# fires on 30 (18.2%), broken down as `the project` 20, `it` 8, `the applicant` 2,
# `they` 1, `the agency` 1. Reviewed by hand: 28 of the 30 carry anaphora whose
# antecedent is in a PREVIOUS sentence ("It comprises 1,086 homeowners", "they
# would fail to eliminate blight", "Moore strongly supported the project"), which
# is exactly what the rule exists to force the decomposer to substitute. The other
# 2 are in-sentence pronouns ("Route 30 ... widening it from", "made it no longer
# feasible") -- still correct at atom level, because splitting the sentence is what
# strands the pronoun. So 18.2% is the WORKLOAD the plan's coreference rule imposes
# on the decomposer, not a false-positive rate. Note the measurement is over source
# prose; the rule itself applies to atom text.
# tests/test_atomic_verify.py::TestCorpusValidators pins the counts so a loosening
# of these rules shows up as a test failure.

_AUX_AFTER_DEMONSTRATIVE = (
    "is", "are", "was", "were", "would", "will", "shall", "should", "may",
    "might", "must", "can", "could", "has", "have", "had", "does", "do", "did",
    "includes", "include", "included", "means", "requires", "results",
)

_WORD_RE = re.compile(r"[A-Za-z][A-Za-z'-]*")
# Expletive `it`: "it is expected that", "it was determined", "it would appear".
_EXPLETIVE_IT = re.compile(
    r"\bit\s+(?:is|was|would\s+be|has\s+been|had\s+been)\s+\w+", re.IGNORECASE
)


def unresolved_references(text: str) -> list[str]:
    """
    Pronouns / generic anaphora still present in an atom's text.

    Non-empty means the atom is not verifiable as written: `quote_check` would
    be asked to confirm "they would be displaced" against a page that names the
    entity explicitly, and the result would be uninterpretable either way.
    """
    s = (text or "").strip()
    if not s:
        return []
    low = s.lower()
    found: list[str] = []

    expletive_spans = [m.span() for m in _EXPLETIVE_IT.finditer(s)]

    for m in _WORD_RE.finditer(low):
        w = m.group(0)
        if w not in PRONOUNS:
            continue
        if w in ("it", "they"):
            if w == "it" and any(a <= m.start() < b for a, b in expletive_spans):
                continue
            found.append(w)
            continue
        # Demonstratives: pronominal only.
        tail = low[m.end():].lstrip()
        if not tail or tail[0] in ".,;:!?":
            found.append(w)
            continue
        nxt = _WORD_RE.match(tail)
        if nxt and nxt.group(0) in _AUX_AFTER_DEMONSTRATIVE:
            found.append(w)

    for phrase in GENERIC_ANAPHORA:
        for m in re.finditer(rf"\b{re.escape(phrase)}\b", low):
            tail = low[m.end():].lstrip()
            nxt = _WORD_RE.match(tail)
            # "the alternatives section", "the project area" -- compound noun,
            # not anaphora. NEPA prose is full of both usages.
            if nxt and nxt.group(0) in COMPOUND_HEADS:
                continue
            if _anaphor_is_self_resolving(phrase, s):
                continue
            found.append(phrase)
            break

    # Preserve first-seen order, drop duplicates.
    seen: dict[str, None] = {}
    for f in found:
        seen.setdefault(f, None)
    return list(seen)


# Nouns that turn a generic anaphor into a compound noun phrase.
COMPOUND_HEADS = frozenset(
    """
    section sections chapter chapters analysis discussion description
    descriptions evaluation list lists area areas table tables appendix
    appendices portion part parts process sponsor sponsors staff site sites
    boundary boundaries limits corridor alignment schedule cost costs
    """.split()
)


def _anaphor_is_self_resolving(phrase: str, text: str) -> bool:
    """
    Whether a generic anaphor's antecedent is spelled out in the same text.

    "The Department of Natural Resources found no significant impact ... the
    department" needs no substitution -- the named form is right there. Without
    this the validator fires on any sentence that names an entity and then refers
    back to it within the sentence, which is ordinary English and not the failure
    MCAL_PLAN 3.4 is guarding against.

    The head noun is matched case-insensitively but the antecedent's proper-noun
    part is not: "Department of the Interior" and "Bad Creek Project" resolve,
    "the project" and "the department" standing alone do not. Determiners are
    excluded from the proper-noun slot -- without that, sentence-initial "The" in
    "The project would include a reservoir" matches as if it were a name.
    """
    head = phrase.split()[-1].rstrip("s") if phrase.split() else ""
    if not head:
        return False
    # "Department of Natural Resources", "Department of the Interior"
    if re.search(rf"(?i:{head}s?)\s+of\s+(?:the\s+)?[A-Z]", text):
        return True
    # "Bad Creek Project", "Airport Spur Project" -- proper-noun modifier.
    if re.search(
        rf"\b(?!{_DETERMINER_ALT}\b)[A-Z][\w'-]*\s+"
        rf"(?:(?!{_DETERMINER_ALT}\b)[A-Z][\w'-]*\s+){{0,3}}(?i:{head}s?)\b",
        text,
    ):
        return True
    return False


# Capitalized words that are not names. Sentence-initial "The"/"This" would
# otherwise satisfy the proper-noun-modifier test for every anaphor.
_DETERMINERS = (
    "The", "A", "An", "This", "That", "These", "Those", "Its", "Their", "Our",
    "Each", "Every", "No", "Any", "All", "Some", "Both", "Such", "One", "Two",
    "Several", "Many", "Most", "Other", "Another", "Only", "In", "On", "At",
    "For", "By", "With", "From", "As", "Of", "To", "If", "When", "Where",
)
_DETERMINER_ALT = "(?:" + "|".join(_DETERMINERS) + ")"


# --- Deterministic validator: negation --------------------------------------

def negation_cues(text: str, *, include_extra: bool = False) -> list[str]:
    """
    Negation cues present in `text`, longest match first.

    Multi-word cues are checked before their single-word constituents so that
    "does not" is reported once rather than as `does not` + `not`.
    """
    low = (text or "").lower()
    if not low:
        return []
    cues = list(NEGATION_CUES) + (list(EXTRA_NEGATION_CUES) if include_extra else [])
    cues.sort(key=len, reverse=True)
    found: list[str] = []
    consumed: list[tuple[int, int]] = []
    for cue in cues:
        for m in re.finditer(rf"\b{re.escape(cue)}\b", low):
            if any(a <= m.start() < b for a, b in consumed):
                continue
            consumed.append(m.span())
            found.append(cue)
            break
    return found


def expected_polarity(text: str) -> str:
    """Polarity the atom text implies, independent of what the model claimed."""
    return "negative" if negation_cues(text) else "affirmative"


# --- Deterministic validator: coordination splitting ------------------------
# MCAL_PLAN 1(4)'s only genuinely catchable failure is a coordinated list item.
# We reimplement the split deterministically for two reasons: to check that the
# decomposer actually split (an under-split atom hides a fabrication behind its
# true neighbours), and so the Lincoln Hwy regression can be demonstrated with
# no LLM in the loop.
#
# This is a heuristic, not a parser, and its scope is deliberately narrow: ONE
# shape, the coordinated SUBJECT list sharing a single predicate --
#
#     "No A, B, or C are affected."  ->  three claims.
#
# That is the wildlife-clause shape. Coordinated OBJECT lists ("the Department
# found no impact on fish or wildlife habitat and no rare species") are NOT
# handled and are left to the model, because attaching a shared subject+verb to
# object fragments needs real argument structure and the naive version produces
# nonsense.
#
# The narrowness is load-bearing. An earlier permissive version accepted any
# sentence with a comma and a trailing auxiliary, and on the 165 graded summary
# sentences it fired on 21 of them producing 74 "claims", most of which were
# garbage cut across clause boundaries ("Of 2 will be cleared", "The project lies
# in Oconee County would need to be relocated"). A validator that reports
# nonsense gaps gets switched off, and then the one real fabrication in the corpus
# goes unnoticed. So: reject anything that is not unambiguously a simple NP list.
#
# With the guards below, the splitter fires on exactly 1 of those 165 sentences
# and yields exactly 3 claims -- the wildlife-clause sentence, which is also the
# only genuine outside-text fabrication in the graded corpus (MCAL_PLAN 1(4)).
# High precision, low recall, by design: the model does the general case, this
# catches the shape that hides fabrications. Pinned by
# tests/test_lincoln_hwy_wildlife_clause.py and
# tests/test_atomic_verify.py::TestCorpusValidators.

_COORD_TAIL = re.compile(
    r",?\s+\b(?:or|and|as well as|along with)\s+", re.IGNORECASE
)
# The shared predicate must begin at the FIRST copula/auxiliary in the sentence
# (re.search is leftmost). Anything earlier than that belongs to the subject.
_SHARED_PREDICATE = re.compile(
    r"\s+((?:are|is|was|were|would|will|shall|can|could|may|might|must|has|have|had)"
    r"\b.*)$",
    re.IGNORECASE,
)
_LEADING_NEGATOR = re.compile(r"^\s*(no|neither|not)\s+", re.IGNORECASE)

# Finite verb forms that, appearing inside the candidate subject span, prove the
# sentence has more than one clause and is therefore out of scope. Generic
# English plus the reporting verbs that dominate `summary.public_response`; not
# derived from the graded corpus's specific wording.
_FINITE_VERBS_IN_SUBJECT = frozenset(
    """
    lies lie lay includes include included comprises comprise consists consist
    contains contain found finds find requested request requests endorsed
    endorse endorses opposed oppose opposes supported support supports noted
    note notes said says stated states praised praise urged urge urges
    recommended recommend recommends revised revise revises planned plan plans
    determined determine determines expressed express expresses cleared clear
    connects connect serves serve serving ranges range saves save affects affect
    requires require provides provide extends extend crosses cross begins begin
    ends end stems stem occurs occur results result remains remain exceeds
    exceed causes cause carries carry displaces displace generates generate
    argued argue argues objected object objects commented comment
    """.split()
)

_MAX_COORD_ITEMS = 6
_MAX_COORD_ITEM_WORDS = 8
_MAX_COORD_SUBJECT_CHARS = 140
_MAX_COORD_PREDICATE_WORDS = 20
# Words that mark a subordinate clause; their presence means the "subject span"
# is not a plain NP list.
_SUBORDINATORS = frozenset(
    "that which who whom whose because although though while whereas since "
    "unless whether when where after before".split()
)
# A second independent clause inside the predicate means the shared predicate is
# not actually shared.
_CLAUSE_JOIN = re.compile(r",\s+(?:and|but|while|whereas|although)\s+|;\s+", re.IGNORECASE)
# Appositive / exemplification markers: these introduce a list that elaborates a
# head noun rather than coordinating separate subjects.
_APPOSITIVE = re.compile(
    r"\b(?:including|such\s+as|e\.g\.|i\.e\.|namely|for\s+example)\b", re.IGNORECASE
)


def coordinated_claims(sentence: str) -> list[str]:
    """
    Split one sentence's coordinated subject list into separate claim strings.

    Returns [] when the sentence is not a simple coordinated subject list, so a
    caller can distinguish "nothing to split" from "split into one". Erring
    towards [] is intentional -- see the block comment above.

    On "No National Register sites, unique wetlands, or important wildlife
    habitats are affected." this returns the three claims, each retaining the
    shared negator and the shared predicate, which is what turns the fabricated
    third item into an independently checkable atom.
    """
    s = " ".join((sentence or "").split()).rstrip(".")
    if not s or not _COORD_TAIL.search(s):
        return []

    m = _SHARED_PREDICATE.search(s)
    if not m:
        return []
    predicate = m.group(1).strip()
    subject_span = s[: m.start()].strip()
    if not subject_span or len(subject_span) > _MAX_COORD_SUBJECT_CHARS:
        return []
    if len(predicate.split()) > _MAX_COORD_PREDICATE_WORDS:
        return []
    if _CLAUSE_JOIN.search(predicate):
        return []
    if _APPOSITIVE.search(subject_span):
        return []
    # An unbalanced bracket means the sentence splitter cut mid-parenthetical and
    # this "subject" is a fragment.
    if subject_span.count("(") != subject_span.count(")"):
        return []

    neg = _LEADING_NEGATOR.match(subject_span)
    negator = neg.group(1) if neg else ""
    if neg:
        subject_span = subject_span[neg.end():]

    subject_words = {w.lower() for w in _WORD_RE.findall(subject_span)}
    if subject_words & _FINITE_VERBS_IN_SUBJECT or subject_words & _SUBORDINATORS:
        return []
    # The coordinator must still be inside the subject span after trimming the
    # predicate; otherwise it coordinated something in the predicate instead.
    if not _COORD_TAIL.search(subject_span):
        return []

    items: list[str] = []
    for part in _COORD_TAIL.split(subject_span):
        for piece in part.split(","):
            piece = piece.strip()
            if piece:
                items.append(piece)
    if not 2 <= len(items) <= _MAX_COORD_ITEMS:
        return []
    if any(
        len(i.split()) > _MAX_COORD_ITEM_WORDS or not _WORD_RE.search(i)
        for i in items
    ):
        return []
    # Parallelism guard. "Rare and endangered species" coordinates two
    # ADJECTIVES sharing one head noun, and "Jackson and Transylvania in NC"
    # coordinates a bare name with a name-plus-modifier; splitting either yields
    # "Rare could be affected". A genuine two-item subject list has items of
    # comparable length, so reject 2-item lists whose first item is a lone word
    # and whose second is not.
    if len(items) == 2 and len(items[0].split()) == 1 and len(items[1].split()) > 1:
        return []

    out = []
    for item in items:
        head = f"{negator} {item}".strip() if negator else item
        out.append(f"{head[0].upper()}{head[1:]} {predicate}.")
    return out


def coordination_gaps(passage: str, atoms: Sequence["Atom"]) -> list[str]:
    """
    Coordinated claims in `passage` that no atom covers.

    Coverage is token-set JACCARD similarity, not containment. Containment is the
    obvious choice and it is wrong here: the failure mode being detected is an
    atom that swallowed the WHOLE sentence, and such an atom contains every
    coordinated claim's tokens, so a containment test would report perfect
    coverage on exactly the input that has none. Jaccard penalizes the extra
    tokens, so the unsplit atom scores 4/9 against each of the three claims and
    all three are reported as gaps, while a correctly split atom scores 1.0.

    A non-empty result means the decomposer under-split, which is the exact
    condition under which a fabricated list item escapes verification behind its
    true neighbours (MCAL_PLAN 1(4)).
    """
    gaps: list[str] = []
    atom_tokens = [set(_significant_tokens(a.text)) for a in atoms]
    for sent in sentences(passage):
        for claim in coordinated_claims(sent):
            want = set(_significant_tokens(claim))
            if not want:
                continue
            covered = False
            for have in atom_tokens:
                union = want | have
                if union and len(want & have) / len(union) >= _COORD_COVER_FLOOR:
                    covered = True
                    break
            if not covered:
                gaps.append(claim)
    return gaps


# Jaccard floor for "this atom is that coordinated claim". 0.6 tolerates the
# decomposer rewording one content word out of four ("National Register sites" ->
# "National Register properties" scores exactly 0.6) while rejecting an atom that
# also carries a sibling's tokens.
_COORD_COVER_FLOOR = 0.6


# --- Deterministic validator: scope qualifiers ------------------------------
# The deviation described in the module docstring. Two directions:
#   * atom-side  -- does this atom make a claim that REQUIRES a qualifier?
#   * source-side -- does the cited sentence carry a qualifier the atom dropped?

# Atom-side cues. Range endpoints, superlatives and comparisons.
SCOPE_CUE_PATTERNS: tuple[tuple[str, str], ...] = (
    ("range", r"\brang(?:e|es|ed|ing)\s+(?:from|between)\b"),
    ("range", r"\bfrom\s+[\$\d][^,;.]{0,40}?\bto\s+[\$\d]"),
    ("bound", r"\b(?:up\s+to|as\s+(?:much|many|few|little|low|high)\s+as|"
              r"at\s+(?:least|most)|a\s+(?:minimum|maximum)\s+of|no\s+more\s+than)\b"),
    ("superlative", r"\b(?:most|least|worst|best|largest|smallest|highest|lowest|"
                    r"greatest|maximum|minimum|peak|maximal)\b"),
    ("comparative", r"\b(?:greater\s+than|more\s+than|less\s+than|fewer\s+than|"
                    r"compared\s+(?:to|with)|relative\s+to|versus|vs\.?)\b"),
)

# Source-side qualifier patterns. High precision on purpose: each one names a
# construction that actually restricts a figure in this corpus. A loose pattern
# here would flag every page that happens to contain the word "most".
QUALIFIER_PATTERNS: tuple[tuple[str, str], ...] = (
    # "For the Rail/Bus Alternatives I-V", "for Alternatives VII - X"
    ("scoped_to_alternatives",
     r"\bfor\s+(?:the\s+)?[\w/\- ]{0,32}?alternatives?\s+[IVXLC0-9][\w\- ]{0,12}"),
    # "of the forty-nine (49) sites"
    ("scoped_to_subset", r"\bof\s+the\s+[\w\-\(\) ]{0,28}?\b(?:sites|structures|"
                         r"alternatives|counties|properties|residences|units)\b"),
    ("maximum_credible", r"\bmaximum\s+(?:credible|expectable|probable)\b"),
    # Superlative plus enough following words to be a comparable phrase.
    ("superlative_scope",
     r"\b(?:most|least|worst|largest|smallest|highest|lowest|greatest|peak)\s+"
     r"(?:\w+\s+){0,4}\w+"),
    # At least one modifier between "the" and the noun. "in the starter line
    # area" restricts; a bare "in the area" does not, and on the Lincoln Hwy
    # pages it is boilerplate that appears in almost every impact sentence.
    ("geographic_scope",
     r"\b(?:within|in|near|along)\s+the\s+(?:\w+\s+){1,3}"
     r"(?:area|zone|corridor|vicinity|boundary|boundaries|limits|reach|segment)\b"),
    ("constant_dollars", r"\bin\s+(?:19|20)\d\d\s+dollars\b"),
    ("design_year", r"\b(?:design[\- ]year|by\s+the\s+year|in\s+the\s+year)\s*(?:19|20)?\d{0,4}"),
    ("exclusion", r"\b(?:excluding|other\s+than|apart\s+from|exclusive\s+of|"
                  r"with\s+the\s+exception\s+of)\b[\w\- ]{0,32}"),
)

_SCOPE_CUE_RES = tuple((name, re.compile(pat, re.IGNORECASE)) for name, pat in SCOPE_CUE_PATTERNS)
_QUALIFIER_RES = tuple((name, re.compile(pat, re.IGNORECASE)) for name, pat in QUALIFIER_PATTERNS)


def scope_cues(text: str) -> list[str]:
    """Names of the range/superlative/comparative cues present in `text`."""
    out: list[str] = []
    for name, rx in _SCOPE_CUE_RES:
        if rx.search(text or "") and name not in out:
            out.append(name)
    return out


def requires_scope_qualifier(atom: "Atom") -> bool:
    """
    Whether MCAL_PLAN-plus-deviation requires this atom to carry a qualifier.

    True for `claim_type == "comparative"` (the type the prompt reserves for
    scoped claims) and for any atom whose own text contains a range, bound,
    superlative or comparison cue -- because a mis-typed atom must not be able to
    opt out of the check by calling itself `numeric`.
    """
    if atom.claim_type == "comparative":
        return True
    return bool(scope_cues(atom.text) or scope_cues(atom.object or ""))


def page_qualifiers(text: str) -> list[tuple[str, str]]:
    """Restricting phrases found in a source fragment, as (pattern_name, phrase)."""
    out: list[tuple[str, str]] = []
    seen: set[str] = set()
    for name, rx in _QUALIFIER_RES:
        for m in rx.finditer(text or ""):
            phrase = " ".join(m.group(0).split())
            key = phrase.lower()
            if key in seen:
                continue
            seen.add(key)
            out.append((name, phrase))
    return out


# Token comparison for qualifier phrases. `quote_check.content_tokens` is wrong
# here: it drops stopwords, and half of a qualifier's information IS its
# function words -- "most", "up to", "other than", "for the ... alternatives".
# So we use a wider token set with only a tiny function-word exclusion.
_QUAL_STOP = frozenset(
    "the a an of to in for on at by with from as and or be is are was were "
    "that this these those it its would will".split()
)


def _significant_tokens(text: str) -> list[str]:
    """Comparable tokens of a short phrase: normalized, >=3 chars, non-trivial."""
    norm = qc.normalize(text or "")
    return [
        t for t in re.findall(r"[a-z0-9]+", norm)
        if (len(t) >= 3 and t not in _QUAL_STOP) or t.isdigit()
    ]


QUALIFIER_CARRIED_FLOOR = 0.6


def qualifier_overlap(phrase: str, haystack: str) -> Optional[float]:
    """
    Fraction of a qualifier phrase's significant tokens present in `haystack`.

    None when the phrase has no comparable tokens.
    """
    want = set(_significant_tokens(phrase))
    if not want:
        return None
    have = set(_significant_tokens(haystack))
    return len(want & have) / len(want)


def qualifier_is_carried(phrase: str, atom_text: str) -> bool:
    """
    Whether `atom_text` reproduces the qualifier `phrase`.

    Token-overlap rather than substring: the summary legitimately rephrases
    ("the maximum credible earthquake" -> "maximum credible"), and demanding an
    exact substring would report every rephrasing as a dropped qualifier.
    """
    cov = qualifier_overlap(phrase, atom_text)
    if cov is None:
        return True  # nothing comparable; do not manufacture a failure
    return cov >= QUALIFIER_CARRIED_FLOOR


def qualifier_verifies(
    qualifier: str,
    haystack: str,
) -> tuple[bool, str]:
    """
    Whether a model-supplied `scope_qualifier` is actually in the cited text.

    Two deliberate choices.

    **Not `quote_check.check_quote`.** Qualifiers are short -- "For the Rail/Bus
    Alternatives I-V" is 33 characters -- and the long note in
    `settings.QUOTE_COVERAGE_YES` measures partial_ratio's chance floor at 50-68
    for strings that short, while the coverage gate cannot even engage because a
    qualifier rarely has three tokens that survive the stopword filter ("for",
    "the", "alternatives" are all filtered). Measured: `check_quote` returns
    "yes" for the p.283 qualifier against LA Transit p.214 purely on sliding-
    window luck, which would have let the cost case pass and defeated the check.
    So we use the same significant-token overlap `qualifier_is_carried` uses --
    symmetric by construction: the atom must carry the qualifier and the source
    must contain it, judged the same way.

    **Localized, not page-window.** `haystack` should be the source fragments
    that actually carry the atom's figure, not the union of `page +/- 2`. A
    qualifier restricts a specific figure, so it has to sit next to that figure.
    Measured on the same case: against the five-page union around p.214 every one
    of the qualifier's four tokens appears *somewhere*, giving overlap 1.00 and a
    false pass; against the table row the figure actually came from, it does not.
    """
    if not (haystack or "").strip():
        return False, "qualifier_source_text_unavailable"
    cov = qualifier_overlap(qualifier, haystack)
    if cov is None:
        return True, "qualifier_has_no_comparable_tokens"
    if cov >= QUALIFIER_CARRIED_FLOOR:
        return True, f"qualifier_token_overlap={cov:.2f}"
    return False, f"qualifier_token_overlap={cov:.2f}"


# --- Advisory diagnostic: competing values ----------------------------------

def competing_values(atom: "Atom", page_text: str) -> list[str]:
    """
    Figures on the cited page that could substitute for this atom's figure.

    ADVISORY ONLY, never gating. This is the only signal that can surface the
    p.145-vs-p.146 magnitude contradiction (the document asserts both 7.0 and
    7.5 for the same fault under different framings), and it is genuinely useful
    to a human reviewer.

    It is not gating because its precision collapses on the OCR'd cost tables
    that dominate this corpus: p.214 of LA Transit is a bare grid of ~40 numbers,
    every one of which is a "competitor" for any cost figure, so a gating version
    would reject essentially every numeric atom cited to a table. Restricting to
    the same magnitude decade keeps the output readable without pretending to a
    precision it does not have.
    """
    mine = qc.numeric_tokens(atom.text) or qc.numeric_tokens(atom.object or "")
    if not mine:
        return []
    try:
        anchors = [float(re.sub(r"[a-z]+$", "", n)) for n in mine]
    except ValueError:  # pragma: no cover - numeric_tokens guarantees parseability
        return []
    anchors = [a for a in anchors if a]

    out: list[str] = []
    for tok in qc.numeric_tokens(page_text):
        stripped = re.sub(r"[a-z]+$", "", tok)
        try:
            v = float(stripped)
        except ValueError:
            continue
        if not v or tok in mine:
            continue
        for a in anchors:
            lo, hi = min(a, v), max(a, v)
            if lo and hi / lo <= 10.0 and tok not in out:
                out.append(tok)
                break
    return out


# --- Atom ------------------------------------------------------------------


@dataclass
class Atom:
    """
    One atomic claim (MCAL_PLAN 3.4, plus `scope_qualifier`).

    `id` is assigned by this module, not by the model: models number atoms
    inconsistently across calls and the id is used as the join key into the
    failure log.
    """

    id: str
    text: str
    subject: str = ""
    predicate: str = ""
    object: str = ""
    page: Optional[int] = None
    evidence_quote: Optional[str] = None
    claim_type: str = DEFAULT_CLAIM_TYPE
    polarity: str = DEFAULT_POLARITY
    coreference_resolved: bool = True
    scope_qualifier: Optional[str] = None
    # Provenance, not part of the plan's schema.
    field: str = ""
    source: str = "decomposed"  # "decomposed" | "claim_verbatim" | "why_notable"
    entry_index: Optional[int] = None

    @property
    def has_citation(self) -> bool:
        return self.page is not None

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "text": self.text,
            "subject": self.subject,
            "predicate": self.predicate,
            "object": self.object,
            "page": self.page,
            "evidence_quote": self.evidence_quote,
            "claim_type": self.claim_type,
            "polarity": self.polarity,
            "coreference_resolved": self.coreference_resolved,
            "scope_qualifier": self.scope_qualifier,
            "field": self.field,
            "source": self.source,
            "entry_index": self.entry_index,
        }


def _coerce_page(value) -> Optional[int]:
    """Model-supplied pages arrive as int, "214", "214-215" or junk."""
    pages = qc.coerce_pages(value)
    return pages[0] if pages else None


def _clean_str(value) -> str:
    return " ".join(str(value).split()) if isinstance(value, (str, int, float)) else ""


def _opt_str(value) -> Optional[str]:
    s = _clean_str(value)
    return s or None


def atom_from_dict(
    raw: dict, *, atom_id: str, field: str = "", source: str = "decomposed",
    entry_index: Optional[int] = None,
) -> Atom:
    """
    Build an Atom from one model-emitted object, coercing loose shapes.

    Unknown `claim_type` / `polarity` values fall back to the schema defaults
    rather than raising: a single mistyped enum should degrade one check, not
    discard an otherwise-usable atom. The substitution is recorded by
    `validate_atom` as a schema violation so it is visible in the log.
    """
    claim_type = _clean_str(raw.get("claim_type")).lower()
    polarity = _clean_str(raw.get("polarity")).lower()
    cor = raw.get("coreference_resolved")
    return Atom(
        id=atom_id,
        text=_clean_str(raw.get("text")),
        subject=_clean_str(raw.get("subject")),
        predicate=_clean_str(raw.get("predicate")),
        object=_clean_str(raw.get("object")),
        page=_coerce_page(raw.get("page")),
        evidence_quote=_opt_str(raw.get("evidence_quote")),
        claim_type=claim_type if claim_type in CLAIM_TYPES else DEFAULT_CLAIM_TYPE,
        polarity=polarity if polarity in POLARITIES else DEFAULT_POLARITY,
        # Absent -> True, matching the schema default. A model that omits the key
        # is asserting nothing; the deterministic check below decides.
        coreference_resolved=True if cor is None else bool(cor),
        scope_qualifier=_opt_str(raw.get("scope_qualifier")),
        field=field,
        source=source,
        entry_index=entry_index,
    )


# --- Schema validation ------------------------------------------------------


def validate_atom(atom: Atom, raw: Optional[dict] = None) -> list[str]:
    """
    Deterministic schema + rule violations for one atom, as reason codes.

    Non-empty means the atom is malformed or breaks a MCAL_PLAN 3.4 rule. These
    are checked BEFORE quote verification because several of them make the
    verification result meaningless rather than merely negative -- verifying
    "they would be displaced" tells you nothing whichever way it comes out.
    """
    problems: list[str] = []

    if not atom.text:
        problems.append("empty_atom_text")

    if raw is not None:
        rt = _clean_str(raw.get("claim_type")).lower()
        if rt and rt not in CLAIM_TYPES:
            problems.append(f"invalid_claim_type:{rt}")
        rp = _clean_str(raw.get("polarity")).lower()
        if rp and rp not in POLARITIES:
            problems.append(f"invalid_polarity:{rp}")

    # Coreference: MCAL_PLAN 3.4 requires coreference_resolved == True before
    # verification runs, and requires the text to be free of anaphora. Check
    # both, because a model can satisfy either one alone.
    if not atom.coreference_resolved:
        problems.append("coreference_unresolved_by_decomposer")
    stale = unresolved_references(atom.text)
    if stale:
        problems.append("unresolved_reference:" + ",".join(stale))

    # Negation: polarity must match the text, and a negative atom's
    # evidence_quote must carry the cue verbatim.
    want_polarity = expected_polarity(atom.text)
    if want_polarity == "negative" and atom.polarity != "negative":
        problems.append(
            "negation_dropped_from_polarity:" + ",".join(negation_cues(atom.text))
        )
    if atom.polarity == "negative":
        if not atom.evidence_quote:
            problems.append("negative_atom_without_evidence_quote")
        elif not negation_cues(atom.evidence_quote):
            problems.append("negation_cue_absent_from_evidence_quote")

    # A `numeric` atom with no figure anywhere is mistyped, and would otherwise
    # silently skip the numeric channel it was routed to.
    if atom.claim_type == "numeric" and not (
        qc.numeric_tokens(atom.text) or qc.numeric_tokens(atom.object or "")
    ):
        problems.append("claim_type_numeric_without_figure")

    # Scope qualifier (documented deviation; see module docstring).
    if requires_scope_qualifier(atom) and not atom.scope_qualifier:
        problems.append("scope_qualifier_missing:" + ",".join(
            scope_cues(atom.text) or scope_cues(atom.object or "") or ["comparative"]
        ))

    return problems


# Reason-code prefixes that map onto a taxonomy tag. Kept as a table so that
# `segment_b/critic.py` and the reviewer's `your_failure_tag` vocabulary can be
# reconciled against one place.
REASON_TAGS: tuple[tuple[str, str], ...] = (
    ("scope_qualifier", "T19_scope_qualifier_dropped"),
    ("uncited", "T01_missing_citation"),
    ("negation", "T02_numeric_hallucination"),
    ("numeric_mismatch", "T02_numeric_hallucination"),
    ("unit_absent", "T02_numeric_hallucination"),
    ("temporal_out_of_tolerance", "T02_numeric_hallucination"),
    ("quote_unverified", "T03_outside_text_fabrication"),
    ("evidence_quote_missing", "T03_outside_text_fabrication"),
    ("unresolved_reference", None),
    ("coreference_unresolved", None),
)


def tags_for_reasons(reasons: Sequence[str]) -> list[str]:
    """Map failure reason codes onto taxonomy tags, in reason order."""
    out: list[str] = []
    for r in reasons:
        for prefix, tag in REASON_TAGS:
            if r.startswith(prefix) and tag and tag not in out:
                out.append(tag)
                break
    return out


# --- Units ------------------------------------------------------------------
# MCAL_PLAN 3.4 asks for "value+unit match" on numeric atoms. Units are checked
# on a soft channel: a missing unit downgrades to `partial`, it does not fail the
# atom. Reason: the figures in this corpus overwhelmingly live in OCR'd tables
# where the unit sits in a column header two rows away from the digits (LA
# Transit p.214 is a grid of bare integers whose "millions of dollars" header is
# on p.213). Hard-failing those would manufacture false negatives on exactly the
# atoms the plan most wants verified. Same downgrade convention as
# quote_check.check_quote's numeric channel.

UNIT_WORDS = (
    "acres", "acre", "miles", "mile", "feet", "foot", "yards", "kilometers",
    "million", "billion", "thousand", "percent", "dollars", "ppm", "dba",
    "tons", "ton", "years", "year", "months", "days", "hours", "structures",
    "sites", "residences", "households", "units", "jobs", "barrels", "gallons",
    "cubic", "square", "degrees", "decibels", "persons", "people", "vehicles",
    "trips", "employees", "families", "parcels", "acre-feet",
)
_UNIT_AFTER_NUMBER = re.compile(
    r"(?:\d[\d,\.]*)\s*(?:%|\b(" + "|".join(UNIT_WORDS) + r")\b)", re.IGNORECASE
)


def units_in(text: str) -> list[str]:
    """Unit words attached to a figure in `text`."""
    out: list[str] = []
    for m in _UNIT_AFTER_NUMBER.finditer(text or ""):
        u = (m.group(1) or "%").lower()
        if u not in out:
            out.append(u)
    return out


# --- Verification result ----------------------------------------------------

STATUS_PASS = "pass"
STATUS_PARTIAL = "partial"
STATUS_FAIL = "fail"

STATUS_SCORES = {STATUS_PASS: 1.0, STATUS_PARTIAL: 0.5, STATUS_FAIL: 0.0}


@dataclass
class AtomResult:
    """Verification outcome for one atom."""

    atom: Atom
    status: str                      # pass | partial | fail
    reasons: list[str] = dc_field(default_factory=list)
    tags: list[str] = dc_field(default_factory=list)
    check: Optional[qc.QuoteCheck] = None
    qualifier_reason: str = ""
    dropped_qualifiers: list[str] = dc_field(default_factory=list)
    competing_values: list[str] = dc_field(default_factory=list)
    matched_page: Optional[int] = None
    source_sentences: list[str] = dc_field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.status == STATUS_PASS

    @property
    def score(self) -> float:
        return STATUS_SCORES[self.status]

    @property
    def weight(self) -> float:
        """2x penalty on numeric/geospatial failures (MCAL_PLAN 3.4)."""
        if self.status != STATUS_PASS and self.atom.claim_type in PENALIZED_CLAIM_TYPES:
            return PENALTY_WEIGHT
        return 1.0

    def to_dict(self) -> dict:
        return {
            "atom": self.atom.to_dict(),
            "status": self.status,
            "score": self.score,
            "weight": self.weight,
            "reasons": self.reasons,
            "tags": self.tags,
            "quote_check": self.check.to_dict() if self.check else None,
            "qualifier_reason": self.qualifier_reason,
            "dropped_qualifiers": self.dropped_qualifiers,
            "competing_values": self.competing_values,
            "matched_page": self.matched_page,
        }

    def log_entry(self, subfield_human_grade: Optional[str]) -> dict:
        """
        One row of `atomic_verify_failure_log.v(N).json`.

        Keys are exactly the six MCAL_PLAN 2 names. Note that MCAL_PLAN 2's
        artifact table calls the last one `subfield_human_grade` while 3.4's
        prose calls it `human_grade_of_subfield`; we use the table's spelling and
        record the inconsistency in the calibration report.
        """
        return {
            "atom_id": self.atom.id,
            "atom_text": self.atom.text,
            "evidence_quote": self.atom.evidence_quote,
            "page": self.atom.page,
            "failure_reason": "; ".join(self.reasons) or self.status,
            "subfield_human_grade": subfield_human_grade,
        }


# --- Per-atom verification --------------------------------------------------


def _locate_source_sentences(
    atom: Atom, page_text: str, *, limit: int = 2
) -> list[str]:
    """
    Fragments of the cited page most likely to be this atom's source.

    Used to localize the qualifier scan. Scanning the whole page would report
    every superlative anywhere on a 4,000-character page as adjacent to the
    atom's figure, which is how a qualifier check turns into noise.

    Ranking prefers fragments containing the atom's figures, then content-token
    overlap with the evidence_quote (the model's own claim about where the
    support is), falling back to the atom text.
    """
    frags = sentences(page_text)
    if not frags:
        return []
    needle = atom.evidence_quote or atom.text
    want = set(qc.content_tokens(qc.normalize(needle)))
    nums = set(qc.numeric_tokens(atom.text) or qc.numeric_tokens(atom.object or ""))

    scored: list[tuple[float, int, str]] = []
    for i, frag in enumerate(frags):
        have = set(qc.content_tokens(qc.normalize(frag)))
        overlap = len(want & have) / len(want) if want else 0.0
        has_num = 1.0 if (nums and nums & set(qc.numeric_tokens(frag))) else 0.0
        if overlap == 0.0 and not has_num:
            continue
        scored.append((has_num + overlap, -i, frag))
    scored.sort(reverse=True)
    return [f for _, _, f in scored[:limit]]


def verify_atom(
    atom: Atom,
    doc: Optional[Doc],
    *,
    tolerance: int = settings.QUOTE_PAGE_TOLERANCE,
    raw: Optional[dict] = None,
) -> AtomResult:
    """
    Verify one atom (MCAL_PLAN 3.4 step 2).

    Order matters. Schema/rule violations are evaluated first: an atom with an
    unresolved pronoun or a dropped negation cannot be meaningfully verified, so
    reporting a quote verdict for it would be misleading. Then the quote check,
    then the type-specific checks.

    Three outcomes rather than two:
      `pass`    -- verdict "yes" and every applicable check satisfied.
      `partial` -- verdict "mixed", or a soft check (unit) failed. Scores 0.5.
      `fail`    -- verdict "no", or a hard check failed. Scores 0.0.
    `partial` counts as a FAILURE for the false-negative audit even though it
    scores 0.5. That is the conservative direction: over-reporting candidate
    false negatives triggers a prompt review (MCAL_PLAN 3.4's stated purpose for
    the log), whereas under-reporting hides the cases the log exists to find.
    """
    reasons = validate_atom(atom, raw)
    hard_fail = bool(reasons)

    # Missing citation. MCAL_PLAN's most common observed failure, and the reason
    # s_citation exists -- it is invisible to s_quote.
    if not atom.has_citation:
        reasons.append("uncited_no_page")
        hard_fail = True
    if not atom.evidence_quote:
        reasons.append("evidence_quote_missing")
        hard_fail = True

    check: Optional[qc.QuoteCheck] = None
    qualifier_reason: str = ""
    dropped: list[str] = []
    competing: list[str] = []
    source_frags: list[str] = []
    status = STATUS_FAIL

    if doc is None:
        reasons.append("no_document_supplied")
        return AtomResult(
            atom=atom, status=STATUS_FAIL, reasons=reasons,
            tags=tags_for_reasons(reasons),
        )

    if atom.has_citation and atom.evidence_quote:
        want_numeric = atom.claim_type == "numeric"
        check = qc.check_quote(
            atom.evidence_quote,
            [atom.page],
            doc,
            tolerance=tolerance,
            require_numeric=want_numeric,
        )
        if check.verified == "yes":
            status = STATUS_PASS
        elif check.verified == "mixed":
            status = STATUS_PARTIAL
            reasons.append(f"quote_partial:{check.reason}")
        else:
            status = STATUS_FAIL
            reasons.append(f"quote_unverified:{check.reason}")

        page_text = ""
        if check.matched_page is not None:
            page_text = next(
                (p.text for p in doc.pages if p.page_num == check.matched_page), ""
            )
            source_frags = _locate_source_sentences(atom, page_text)

        # --- type-specific checks (MCAL_PLAN 3.4 step 2) ---
        if atom.claim_type == "numeric":
            if check.numeric_ok is False:
                reasons.append(f"numeric_mismatch:{check.missing_numbers}")
                status = STATUS_FAIL
            missing_units = _missing_units(atom, page_text)
            if missing_units:
                reasons.append("unit_absent:" + ",".join(missing_units))
                if status == STATUS_PASS:
                    status = STATUS_PARTIAL

        elif atom.claim_type == "temporal":
            ok, why = _temporal_within_tolerance(atom, page_text)
            if not ok:
                reasons.append(why)
                status = STATUS_FAIL

        if atom.polarity == "negative":
            haystack = " ".join(source_frags) or page_text
            if not negation_cues(haystack):
                reasons.append("negation_cue_absent_from_source")
                status = STATUS_FAIL

        # --- scope qualifier (documented deviation) ---
        # Both directions run against the same localized text: the fragments of
        # the matched page that carry this atom's figure. Falls back to the whole
        # matched page only when no fragment could be localized, which is the
        # case for bare OCR'd tables with no sentence structure at all.
        #
        # Skipped entirely when the quote did not verify at all. On an atom whose
        # evidence is absent from the page, the "located source sentences" are
        # whatever happened to share a few tokens, so any qualifier found in them
        # is unrelated to the atom. The atom already fails; adding a spurious
        # `scope_qualifier_dropped` reason would inflate T19 in
        # `reason_code_counts`, which is a diagnostic the next prompt revision is
        # read from.
        qualifier_source = " ".join(source_frags) or page_text
        localized = check.verified != "no"
        if atom.scope_qualifier:
            ok, why = qualifier_verifies(atom.scope_qualifier, qualifier_source)
            qualifier_reason = why
            if not ok:
                reasons.append(f"scope_qualifier_unverified:{why}")
                status = STATUS_FAIL
        if localized:
            for _name, phrase in page_qualifiers(qualifier_source):
                carrier = f"{atom.text} {atom.scope_qualifier or ''}"
                if not qualifier_is_carried(phrase, carrier):
                    dropped.append(phrase)
            if dropped:
                reasons.append("scope_qualifier_dropped:" + " | ".join(dropped))
                status = STATUS_FAIL

        # --- advisory ---
        # Same locality condition: competing figures on a page the atom does not
        # actually come from tell a reviewer nothing.
        if page_text and localized:
            competing = competing_values(atom, page_text)

    if hard_fail:
        status = STATUS_FAIL

    return AtomResult(
        atom=atom,
        status=status,
        reasons=reasons,
        tags=tags_for_reasons(reasons),
        check=check,
        qualifier_reason=qualifier_reason,
        dropped_qualifiers=dropped,
        competing_values=competing,
        matched_page=check.matched_page if check else None,
        source_sentences=source_frags,
    )


def _missing_units(atom: Atom, page_text: str) -> list[str]:
    """Unit words the atom attaches to a figure but the matched page lacks."""
    if not page_text:
        return []
    want = units_in(f"{atom.text} {atom.object or ''}")
    if not want:
        return []
    page_norm = qc.normalize(page_text)
    missing = []
    for u in want:
        if u == "%":
            # Punctuation is stripped by normalize(); look for the word form.
            if "percent" not in page_norm and "%" not in page_text:
                missing.append(u)
            continue
        if qc.normalize(u) not in page_norm:
            missing.append(u)
    return missing


_YEAR_RE = re.compile(r"\b(1[89]\d\d|20\d\d)\b")
TEMPORAL_YEAR_TOLERANCE = 1


def _temporal_within_tolerance(atom: Atom, page_text: str) -> tuple[bool, str]:
    """
    MCAL_PLAN 3.4: `temporal` -> date within +/-1yr tolerance.

    A temporal atom carrying no year (durations: "over 30 years") has nothing to
    compare, so it passes this check and is judged on its quote verdict alone.
    The tolerance exists because OCR routinely damages a digit in a four-digit
    year on these scans, and because summaries round a fiscal year to a calendar
    one; it is deliberately NOT applied through the numeric channel, which is
    exact by design (7.5 != 7.0).
    """
    claimed = [int(y) for y in _YEAR_RE.findall(f"{atom.text} {atom.object or ''}")]
    if not claimed:
        return True, ""
    if not page_text:
        return False, "temporal_out_of_tolerance:no_page_text"
    page_years = {int(y) for y in _YEAR_RE.findall(page_text)}
    if not page_years:
        return False, f"temporal_out_of_tolerance:no_year_on_page:{claimed}"
    for y in claimed:
        if not any(abs(y - p) <= TEMPORAL_YEAR_TOLERANCE for p in page_years):
            return (
                False,
                f"temporal_out_of_tolerance:{y}_vs_{sorted(page_years)[:6]}",
            )
    return True, ""


# --- Aggregation ------------------------------------------------------------


def aggregate_score(results: Sequence[AtomResult]) -> float:
    """
    `subfield_score = mean(atomic_scores)` with a 2x penalty on numeric and
    geospatial failures (MCAL_PLAN 3.4).

    Implemented as a WEIGHTED mean -- failed numeric/geospatial atoms count
    twice in the denominator as well as the numerator -- rather than by
    subtracting a penalty term. Two reasons: the result stays in [0, 1], which it
    must, because this score feeds `composite` and is compared against tau; and
    the magnitude of the penalty then does not depend on how many atoms the
    subfield happens to have. Subtracting 2x per failure would make a 3-atom
    subfield with one numeric failure score below zero while a 20-atom subfield
    with the same failure barely moved.

    No atoms -> 0.0. An undecomposable subfield is not a verified one.
    """
    if not results:
        return 0.0
    num = sum(r.weight * r.score for r in results)
    den = sum(r.weight for r in results)
    return max(0.0, min(1.0, num / den)) if den else 0.0


def s_citation(atoms_or_results: Sequence) -> Optional[float]:
    """
    MCAL_PLAN 3.3 `s_citation`: fraction of atomic claims with a page cite.

    Returns None for an empty sequence, which is what
    `confidence.compute_signals(citation_rate=...)` expects for "not measured" --
    distinct from 0.0, which means "measured, and no atom was cited".

    Accepts Atoms or AtomResults so callers do not have to unwrap.
    """
    atoms = [
        (x.atom if isinstance(x, AtomResult) else x) for x in atoms_or_results
    ]
    if not atoms:
        return None
    return sum(1 for a in atoms if a.has_citation) / len(atoms)


def s_citation_verified(results: Sequence[AtomResult]) -> Optional[float]:
    """
    Stricter variant: fraction of atoms whose cite actually resolved.

    Diagnostic only. `s_citation` is the plan's definition and is what feeds the
    signal vector; this one distinguishes "cited a page" from "cited a page that
    supports the claim", which is the difference between the two halves of
    T01_missing_citation ("no page cite, OR cites a page that does not support
    it" -- taxonomy.py T01).
    """
    if not results:
        return None
    good = sum(
        1 for r in results
        if r.atom.has_citation and r.check is not None and r.check.verified != "no"
    )
    return good / len(results)


# --- Decomposition (Opus) ---------------------------------------------------

MAX_TOKENS = 4000


def _default_call(system: str, user: str, **kw) -> dict:
    """
    The single Opus call.

    Imported lazily so that importing this module -- and running its entire
    deterministic half in tests -- needs neither the Anthropic SDK nor
    credentials. Routing is Opus per MCAL_PLAN 3.4 / 7 Q2; `settings.MODEL_OPUS`
    is the id of record.
    """
    import llm  # segment_a, JSON-only wrapper

    return llm.call_json(settings.MODEL_OPUS, system, user, **kw)


def build_decomposition_user_prompt(
    field: str,
    passage: str,
    evidence: Sequence[dict],
    doc: Optional[Doc],
    *,
    tolerance: int = settings.QUOTE_PAGE_TOLERANCE,
    max_page_chars: int = 60_000,
) -> str:
    """
    User half of the decomposition prompt.

    Carries the passage, its citations, and the OCR text of `cited +/- 2` with
    `[[PAGE n]]` markers -- the same EVIDENCE shape MCAL_PLAN 7 Q3 fixes for the
    Critic. The page text is what makes rule 1 of the scope-qualifier section
    ("copy it verbatim from the cited page") satisfiable at all; without it the
    model would have to invent qualifiers from the summary, which is the failure
    we are trying to detect.
    """
    cited: list[int] = []
    for ev in evidence or []:
        cited.extend(qc.coerce_pages(ev.get("source_pages")))
    cited = sorted(set(cited))

    lines = [
        f"FIELD: {field}",
        "",
        "PASSAGE TO DECOMPOSE:",
        passage.strip() or "(empty)",
        "",
        "CITATIONS SUPPLIED WITH THIS PASSAGE:",
    ]
    if evidence:
        for ev in evidence:
            pages = qc.coerce_pages(ev.get("source_pages"))
            quote = " ".join((ev.get("quote") or "").split())
            lines.append(f"- pages {pages or 'NONE'}: {quote}")
    else:
        lines.append(
            "- NONE. Every atom you emit must therefore have page: null. Do not "
            "guess page numbers."
        )

    lines.append("")
    lines.append("EVIDENCE (OCR text of the cited pages +/- 2):")
    if doc is not None and cited:
        window = qc.expand_with_tolerance(cited, tolerance)
        budget = max_page_chars
        for p in doc.pages:
            if p.page_num not in window:
                continue
            body = p.text or ""
            if budget <= 0:
                lines.append(f"[[PAGE {p.page_num}]] (omitted: prompt budget)")
                continue
            if len(body) > budget:
                body = body[:budget] + "\n(...truncated)"
            budget -= len(body)
            lines.append(f"[[PAGE {p.page_num}]]")
            lines.append(body)
    else:
        lines.append("(no cited pages resolvable; verification will fail these atoms)")

    return "\n".join(lines)


def _atom_id(field: str, index: int, *, suffix: str = "") -> str:
    slug = field.replace(".", "_")
    return f"{slug}.a{index:02d}{suffix}"


def decompose(
    field: str,
    passage: str,
    evidence: Sequence[dict],
    doc: Optional[Doc],
    *,
    call: Optional[Callable[..., dict]] = None,
    max_tokens: int = MAX_TOKENS,
    tolerance: int = settings.QUOTE_PAGE_TOLERANCE,
    source: str = "decomposed",
    entry_index: Optional[int] = None,
    id_suffix: str = "",
) -> tuple[list[Atom], list[dict], list[str]]:
    """
    One Opus decomposition call. Returns `(atoms, raw_objects, warnings)`.

    `call` injects the LLM function so tests need no network; the default is a
    lazy `llm.call_json(settings.MODEL_OPUS, ...)`.

    A failed or malformed call yields `([], [], [warning])` rather than raising.
    An undecomposable subfield scores 0.0 in aggregation, which routes it to
    HUMAN_REVIEW -- the correct outcome, and strictly better than aborting a
    whole calibration build because one Opus call returned prose.

    Ids are assigned here and overwrite anything the model supplied: they are the
    join key into `atomic_verify_failure_log.v(N).json` and must be stable across
    reruns of the same stage.
    """
    warnings: list[str] = []
    text = (passage or "").strip()
    if not text:
        return [], [], ["empty_passage"]

    system = load_prompt_template()
    user = build_decomposition_user_prompt(
        field, text, evidence, doc, tolerance=tolerance
    )
    fn = call or _default_call
    try:
        out = fn(system, user, max_tokens=max_tokens)
    except Exception as e:  # noqa: BLE001 - one bad call must not stop the build
        log.warning("atomic decomposition failed for %s: %s", field, e)
        return [], [], [f"decomposition_call_failed:{type(e).__name__}"]

    raw_list = None
    if isinstance(out, dict):
        raw_list = out.get("atoms")
    elif isinstance(out, list):
        raw_list = out
    if not isinstance(raw_list, list):
        warnings.append(f"decomposition_returned_{type(raw_list).__name__}_not_list")
        return [], [], warnings

    atoms: list[Atom] = []
    raws: list[dict] = []
    for i, raw in enumerate(raw_list, 1):
        if not isinstance(raw, dict):
            warnings.append(f"atom_{i}_not_an_object")
            continue
        atom = atom_from_dict(
            raw,
            atom_id=_atom_id(field, len(atoms) + 1, suffix=id_suffix),
            field=field,
            source=source,
            entry_index=entry_index,
        )
        if not atom.text:
            warnings.append(f"atom_{i}_has_no_text")
            continue
        atoms.append(atom)
        raws.append(raw)

    if not atoms:
        warnings.append("decomposition_yielded_no_atoms")
    return atoms, raws, warnings


# --- Subfield verification --------------------------------------------------


@dataclass
class FieldVerification:
    """Atomic-verification result for one field of one document."""

    doc_id: str
    field: str
    bucket: str
    results: list[AtomResult] = dc_field(default_factory=list)
    warnings: list[str] = dc_field(default_factory=list)
    coordination_gaps: list[str] = dc_field(default_factory=list)

    @property
    def score(self) -> float:
        return aggregate_score(self.results)

    @property
    def n_atoms(self) -> int:
        return len(self.results)

    @property
    def n_failed(self) -> int:
        return sum(1 for r in self.results if not r.ok)

    @property
    def s_citation(self) -> Optional[float]:
        return s_citation(self.results)

    @property
    def tags(self) -> list[str]:
        out: list[str] = []
        for r in self.results:
            for t in r.tags:
                if t not in out:
                    out.append(t)
        return out

    def failures(self) -> list[AtomResult]:
        return [r for r in self.results if not r.ok]

    def to_dict(self) -> dict:
        return {
            "doc_id": self.doc_id,
            "field": self.field,
            "bucket": self.bucket,
            "subfield_score": round(self.score, 6),
            "s_citation": (
                None if self.s_citation is None else round(self.s_citation, 6)
            ),
            "s_citation_verified": (
                None if s_citation_verified(self.results) is None
                else round(s_citation_verified(self.results), 6)
            ),
            "n_atoms": self.n_atoms,
            "n_failed": self.n_failed,
            "tags": self.tags,
            "coordination_gaps": self.coordination_gaps,
            "warnings": self.warnings,
            "atoms": [r.to_dict() for r in self.results],
        }


def verify_subfield(
    doc_id: str,
    field: str,
    value: dict,
    doc: Optional[Doc],
    *,
    call: Optional[Callable[..., dict]] = None,
    atoms: Optional[Sequence[Atom]] = None,
    raws: Optional[Sequence[dict]] = None,
    tolerance: int = settings.QUOTE_PAGE_TOLERANCE,
) -> FieldVerification:
    """
    Decompose and verify one `summary.*` subfield.

    `value` is the segment_a M2 shape `{text, evidence: [{quote, source_pages}]}`.
    Pass `atoms=` to verify a decomposition you already have (tests, reruns).
    """
    bucket = settings.bucket_for_field(field)
    passage = (value or {}).get("text") or ""
    evidence = (value or {}).get("evidence") or []

    warnings: list[str] = []
    if atoms is None:
        atoms, raws, warnings = decompose(
            field, passage, evidence, doc, call=call, tolerance=tolerance
        )
    raw_by_index = list(raws or [])

    results = [
        verify_atom(
            a, doc, tolerance=tolerance,
            raw=raw_by_index[i] if i < len(raw_by_index) else None,
        )
        for i, a in enumerate(atoms)
    ]

    gaps = coordination_gaps(passage, atoms) if atoms else []
    if gaps:
        warnings.append(f"coordination_under_split:{len(gaps)}")

    return FieldVerification(
        doc_id=settings.normalize_doc_id(doc_id),
        field=field,
        bucket=bucket,
        results=results,
        warnings=warnings,
        coordination_gaps=gaps,
    )


# --- summary_of_interest ----------------------------------------------------

SOI_CLAIM_SUFFIX = "c"
SOI_WHY_SUFFIX = "w"

T17 = "T17_manufactured_salience"


def claim_atom(entry: dict, *, index: int, field: str = settings.SUMMARY_OF_INTEREST) -> Atom:
    """
    Turn one `summary_of_interest` entry's `claim` into an atom WITHOUT calling
    the decomposer (MCAL_PLAN 3.4).

    The plan is explicit that decomposition is a no-op for `claim`: each entry is
    already claim-shaped (`{claim, salience_criterion, page, evidence_quote,
    why_notable}`), so it goes straight to per-atom verification. Running Opus on
    it would only add a paraphrase step between the extraction and the check,
    which is precisely the coupling atomic verification exists to remove.

    Type is inferred rather than model-supplied, because there is no model call:
    a claim carrying a range/superlative cue is `comparative` (and therefore
    subject to the qualifier check), one carrying a bare figure is `numeric`,
    otherwise `prose`.
    """
    claim = _clean_str(entry.get("claim"))
    quote = _opt_str(entry.get("evidence_quote"))
    page = _coerce_page(entry.get("page"))
    if page is None:
        for ev in entry.get("evidence") or []:
            page = _coerce_page((ev or {}).get("source_pages"))
            if page is not None:
                break

    if scope_cues(claim):
        claim_type = "comparative"
    elif qc.numeric_tokens(claim):
        claim_type = "numeric"
    else:
        claim_type = "prose"

    return Atom(
        id=_atom_id(field, index + 1, suffix=SOI_CLAIM_SUFFIX),
        text=claim,
        subject=_clean_str(entry.get("salience_criterion")),
        predicate="is notable because",
        object="",
        page=page,
        evidence_quote=quote,
        claim_type=claim_type,
        polarity=expected_polarity(claim),
        coreference_resolved=not unresolved_references(claim),
        scope_qualifier=None,
        field=field,
        source="claim_verbatim",
        entry_index=index,
    )


@dataclass
class SoiEntryVerification:
    """Per-entry result for `summary_of_interest` (MCAL_PLAN 3.4, 3.15)."""

    index: int
    salience_criterion: str
    claim_result: AtomResult
    why_results: list[AtomResult] = dc_field(default_factory=list)
    warnings: list[str] = dc_field(default_factory=list)

    @property
    def claim_ok(self) -> bool:
        return self.claim_result.ok

    @property
    def why_ok(self) -> bool:
        """Empty `why_notable` is NOT ok: MCAL_PLAN 3.15 rule 1 requires it."""
        return bool(self.why_results) and all(r.ok for r in self.why_results)

    @property
    def manufactured_salience(self) -> bool:
        """
        MCAL_PLAN 3.4: claim verifies but why_notable does not -> T17.

        This is the specific asymmetry the plan names. A verifying claim with a
        non-verifying rationale means the entry found real text and then
        explained its significance from general NEPA knowledge -- the definition
        of manufactured salience. Both failing is a plain unsupported entry, not
        T17, and is tagged by the atom's own reasons.
        """
        return self.claim_ok and not self.why_ok

    @property
    def results(self) -> list[AtomResult]:
        return [self.claim_result] + list(self.why_results)

    def to_dict(self) -> dict:
        return {
            "index": self.index,
            "salience_criterion": self.salience_criterion,
            "claim_ok": self.claim_ok,
            "why_notable_ok": self.why_ok,
            "manufactured_salience": self.manufactured_salience,
            "tags": [T17] if self.manufactured_salience else [],
            "claim": self.claim_result.to_dict(),
            "why_notable": [r.to_dict() for r in self.why_results],
            "warnings": self.warnings,
        }


def verify_summary_of_interest(
    doc_id: str,
    entries: Sequence[dict],
    doc: Optional[Doc],
    *,
    call: Optional[Callable[..., dict]] = None,
    tolerance: int = settings.QUOTE_PAGE_TOLERANCE,
    why_atoms_by_entry: Optional[dict[int, Sequence[Atom]]] = None,
) -> tuple[FieldVerification, list[SoiEntryVerification]]:
    """
    Verify `summary_of_interest` (MCAL_PLAN 3.4, 3.15).

    `claim` is verified verbatim (no decomposition). `why_notable` IS decomposed
    and verified separately, because that sentence is where unsupported
    editorializing appears. An entry whose `claim` verifies but whose
    `why_notable` does not is tagged `T17_manufactured_salience`.

    An EMPTY entry list is a correct and expected result for a routine document
    (MCAL_PLAN 3.15 rule 2) and yields an empty FieldVerification with a note --
    NOT a score of 0.0 attributed to a defect. The caller must not conflate
    "nothing notable here" with "the field failed", which is why
    `aggregate_score`'s empty-list 0.0 is annotated in `warnings` here.

    `why_atoms_by_entry` injects pre-computed why_notable decompositions so tests
    can exercise the T17 logic without an LLM.
    """
    field = settings.SUMMARY_OF_INTEREST
    per_entry: list[SoiEntryVerification] = []
    all_results: list[AtomResult] = []
    warnings: list[str] = []

    if not entries:
        warnings.append(
            "summary_of_interest is empty. MCAL_PLAN 3.15 rule 2: an empty list "
            "is a CORRECT result for a routine document. Score 0.0 here means "
            "'no atoms to verify', not 'the field is wrong'."
        )
        return (
            FieldVerification(
                doc_id=settings.normalize_doc_id(doc_id),
                field=field,
                bucket=settings.bucket_for_field(field),
                results=[],
                warnings=warnings,
            ),
            [],
        )

    for i, entry in enumerate(entries):
        if not isinstance(entry, dict):
            warnings.append(f"soi_entry_{i}_not_an_object")
            continue
        entry_warnings: list[str] = []

        c_atom = claim_atom(entry, index=i, field=field)
        c_result = verify_atom(c_atom, doc, tolerance=tolerance)

        why = _clean_str(entry.get("why_notable"))
        if why_atoms_by_entry is not None and i in why_atoms_by_entry:
            w_atoms = list(why_atoms_by_entry[i])
            w_raws: list[dict] = []
        elif not why:
            w_atoms, w_raws = [], []
            entry_warnings.append("why_notable_empty")
        else:
            w_atoms, w_raws, w_warn = decompose(
                field,
                why,
                entry.get("evidence") or _evidence_from_entry(entry),
                doc,
                call=call,
                tolerance=tolerance,
                source="why_notable",
                entry_index=i,
                id_suffix=f"{SOI_WHY_SUFFIX}{i + 1}",
            )
            entry_warnings.extend(w_warn)

        w_results = [
            verify_atom(a, doc, tolerance=tolerance,
                        raw=w_raws[j] if j < len(w_raws) else None)
            for j, a in enumerate(w_atoms)
        ]

        ev = SoiEntryVerification(
            index=i,
            salience_criterion=_clean_str(entry.get("salience_criterion")),
            claim_result=c_result,
            why_results=w_results,
            warnings=entry_warnings,
        )
        if ev.manufactured_salience and T17 not in c_result.tags:
            # Attach T17 to the claim atom's result so the tag surfaces in
            # FieldVerification.tags without a second traversal.
            c_result.tags.append(T17)
            c_result.reasons.append("why_notable_unsupported_while_claim_verifies")
        per_entry.append(ev)
        all_results.extend(ev.results)

    fv = FieldVerification(
        doc_id=settings.normalize_doc_id(doc_id),
        field=field,
        bucket=settings.bucket_for_field(field),
        results=all_results,
        warnings=warnings,
    )
    return fv, per_entry


def _evidence_from_entry(entry: dict) -> list[dict]:
    """Synthesize an evidence list from a flat summary_of_interest entry."""
    page = _coerce_page(entry.get("page"))
    quote = _opt_str(entry.get("evidence_quote"))
    if page is None and quote is None:
        return []
    return [{"quote": quote or "", "source_pages": [page] if page else []}]


# --- Document-level orchestration -------------------------------------------


@dataclass
class DocumentVerification:
    """All atomic verification for one document."""

    doc_id: str
    fields: dict[str, FieldVerification] = dc_field(default_factory=dict)
    soi_entries: list[SoiEntryVerification] = dc_field(default_factory=list)

    def all_results(self) -> list[AtomResult]:
        return [r for fv in self.fields.values() for r in fv.results]

    def citation_rates(self) -> dict[str, Optional[float]]:
        """
        `{field: s_citation}`, shaped for
        `confidence.compute_signals(citation_rate=...)`.

        This is the handoff described in the module docstring: it is the only
        signal that can see T01_missing_citation, and confidence.py consumes it
        per field with no reshaping.
        """
        return {f: fv.s_citation for f, fv in self.fields.items()}

    def subfield_scores(self) -> dict[str, float]:
        return {f: fv.score for f, fv in self.fields.items()}

    def to_dict(self) -> dict:
        return {
            "doc_id": self.doc_id,
            "subfield_scores": {
                f: round(s, 6) for f, s in self.subfield_scores().items()
            },
            "citation_rates": {
                f: (None if v is None else round(v, 6))
                for f, v in self.citation_rates().items()
            },
            "n_atoms": len(self.all_results()),
            "n_failed": sum(1 for r in self.all_results() if not r.ok),
            "fields": {f: fv.to_dict() for f, fv in self.fields.items()},
            "summary_of_interest_entries": [e.to_dict() for e in self.soi_entries],
        }


def verify_document(
    doc_id: str,
    m2: dict,
    doc: Optional[Doc],
    *,
    call: Optional[Callable[..., dict]] = None,
    fields: Sequence[str] = settings.ATOMIC_VERIFY_FIELDS,
    tolerance: int = settings.QUOTE_PAGE_TOLERANCE,
) -> DocumentVerification:
    """
    Decompose and verify every in-scope field of one document's M2 output.

    Scope defaults to `settings.ATOMIC_VERIFY_FIELDS` -- the five summary
    subfields plus `summary_of_interest`. One Opus call per summary subfield plus
    one per non-empty `why_notable`; `summary_of_interest.claim` costs nothing
    (decomposition is a no-op there per MCAL_PLAN 3.4).
    """
    out = DocumentVerification(doc_id=settings.normalize_doc_id(doc_id))
    summary = (m2 or {}).get("summary") or {}

    for field in fields:
        if field == settings.SUMMARY_OF_INTEREST:
            entries = (m2 or {}).get(settings.SUMMARY_OF_INTEREST) or []
            fv, per_entry = verify_summary_of_interest(
                doc_id, entries, doc, call=call, tolerance=tolerance
            )
            out.fields[field] = fv
            out.soi_entries = per_entry
            continue

        sub = field.split(".", 1)[1] if "." in field else field
        value = summary.get(sub)
        if not isinstance(value, dict):
            value = {"text": value or "", "evidence": []}
        out.fields[field] = verify_subfield(
            doc_id, field, value, doc, call=call, tolerance=tolerance
        )
    return out


# --- False-negative audit (MCAL_PLAN 3.4, 6) --------------------------------


def false_negative_audit(
    verifications: Sequence[DocumentVerification],
    grade_set,
    *,
    stage: str,
) -> dict:
    """
    False-negative rate on CORRECTLY-graded subfields (MCAL_PLAN 3.4, 6).

    A failing atom inside a subfield the human graded CORRECT is a candidate
    false negative: the human read the whole subfield and found nothing wrong, so
    either the verifier is wrong or the human missed something. Either is worth
    knowing; neither is knowable without the log.

    Advisory at v1 and GATING from
    `settings.ATOMIC_FALSE_NEGATIVE_GATING_FROM_STAGE` (v2), per MCAL_PLAN 3.4.
    The advisory window is not politeness: at n=9 the atoms drawn from
    correctly-graded subfields number roughly 15-25, so a single verifier quirk
    moves the rate by 4-7 points and the 10% ceiling would be decided by noise.

    `flagged` True means the build must not freeze without a decomposition-prompt
    review. Returns the numbers either way so the report can show them.
    """
    stage_n = settings.stage_number(stage)
    gating = stage_n >= settings.ATOMIC_FALSE_NEGATIVE_GATING_FROM_STAGE

    n_atoms = 0
    n_fn = 0
    per_field: dict[str, dict] = {}
    examples: list[dict] = []

    for dv in verifications:
        for field, fv in dv.fields.items():
            grade = grade_set.get(dv.doc_id, field) if grade_set is not None else None
            if grade is None or not grade.correct:
                continue
            bucket = per_field.setdefault(
                field, {"n_atoms": 0, "n_false_negatives": 0, "docs": []}
            )
            bucket["n_atoms"] += fv.n_atoms
            bucket["n_false_negatives"] += fv.n_failed
            if dv.doc_id not in bucket["docs"]:
                bucket["docs"].append(dv.doc_id)
            n_atoms += fv.n_atoms
            n_fn += fv.n_failed
            for r in fv.failures():
                examples.append(
                    {
                        "doc_id": dv.doc_id,
                        "field": field,
                        **r.log_entry(grade.raw_grade),
                    }
                )

    rate = (n_fn / n_atoms) if n_atoms else None
    exceeds = bool(rate is not None and rate > settings.ATOMIC_FALSE_NEGATIVE_CEILING)

    notes: list[str] = []
    if n_atoms and n_atoms < 30:
        notes.append(
            f"Only {n_atoms} atoms were drawn from correctly-graded subfields. "
            f"MCAL_PLAN 3.4 anticipates ~15-25 at seed v1 and calls the rate "
            f"advisory for exactly this reason: one atom is worth "
            f"{100 / n_atoms:.1f} percentage points."
        )
    if rate is None:
        notes.append(
            "No atoms from correctly-graded subfields. Either no grades were "
            "supplied, or every in-scope subfield of every graded doc is graded "
            "wrong; check the grade set before reading this as a clean result."
        )

    return {
        "stage": settings.normalize_stage(stage),
        "gating": gating,
        "gating_from_stage": f"v{settings.ATOMIC_FALSE_NEGATIVE_GATING_FROM_STAGE}",
        "ceiling": settings.ATOMIC_FALSE_NEGATIVE_CEILING,
        "n_atoms_on_correct_subfields": n_atoms,
        "n_false_negatives": n_fn,
        "false_negative_rate": None if rate is None else round(rate, 4),
        "exceeds_ceiling": exceeds,
        # The one field a build orchestrator has to read.
        "flagged": bool(gating and exceeds),
        "per_field": per_field,
        "notes": notes,
        "examples": examples[:50],
    }


# --- Artifacts --------------------------------------------------------------


def _write_json(path: Path, payload) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    return path


def atomic_schema() -> dict:
    """
    The `atomic_schema.v(N).json` payload (MCAL_PLAN 2).

    A real JSON Schema, not a prose description: `segment_b/critic.py` and any
    reviewer tooling need to validate atom tuples they did not produce, and the
    Critic prompt cites the same field names.
    """
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "M-Cal atomic claim",
        "description": (
            "One atomic factual claim produced by mcal/atomic_verify.py "
            "(MCAL_PLAN 3.4). `scope_qualifier` is an addition to the plan's "
            "schema; see the atomic_verify.py module docstring for the empirical "
            "justification and mcal/taxonomy.py T19_scope_qualifier_dropped."
        ),
        "type": "object",
        "additionalProperties": False,
        "required": [
            "id", "text", "subject", "predicate", "object", "page",
            "evidence_quote", "claim_type", "polarity", "coreference_resolved",
            "scope_qualifier",
        ],
        "properties": {
            "id": {"type": "string", "description": "stable join key into the failure log"},
            "text": {"type": "string", "minLength": 1},
            "subject": {"type": "string"},
            "predicate": {"type": "string"},
            "object": {"type": "string"},
            "page": {
                "type": ["integer", "null"],
                "minimum": 1,
                "description": "null is a finding (T01_missing_citation), not an omission",
            },
            "evidence_quote": {
                "type": ["string", "null"],
                "description": "verbatim substring of the cited page, >=20 chars, or null",
            },
            "claim_type": {"type": "string", "enum": list(CLAIM_TYPES)},
            "polarity": {
                "type": "string",
                "enum": list(POLARITIES),
                "default": DEFAULT_POLARITY,
            },
            "coreference_resolved": {"type": "boolean", "default": True},
            "scope_qualifier": {
                "type": ["string", "null"],
                "description": (
                    "verbatim restricting phrase from the cited page. REQUIRED "
                    "for range endpoints, superlatives and comparisons."
                ),
            },
            "field": {"type": "string"},
            "source": {
                "type": "string",
                "enum": ["decomposed", "claim_verbatim", "why_notable"],
            },
            "entry_index": {"type": ["integer", "null"]},
        },
        "x-mcal": {
            "claim_types": list(CLAIM_TYPES),
            "polarities": list(POLARITIES),
            "negation_cues": list(NEGATION_CUES),
            "coordinators": list(COORDINATORS),
            "pronouns_requiring_resolution": list(PRONOUNS),
            "generic_anaphora": list(GENERIC_ANAPHORA),
            "penalized_claim_types": sorted(PENALIZED_CLAIM_TYPES),
            "penalty_weight": PENALTY_WEIGHT,
            "temporal_year_tolerance": TEMPORAL_YEAR_TOLERANCE,
            "page_tolerance": settings.QUOTE_PAGE_TOLERANCE,
            "scope_qualifier_is_a_deviation": True,
            "scope_qualifier_tag": "T19_scope_qualifier_dropped",
        },
    }


def save_atomic_schema(stage: str, *, draft: bool = True) -> Path:
    """Write `atomic_schema.v(N).json`."""
    payload = atomic_schema()
    payload["version"] = settings.normalize_stage(stage)
    return _write_json(
        settings.artifact_path("atomic_schema.json", stage, draft=draft), payload
    )


def build_failure_log(
    verifications: Sequence[DocumentVerification],
    grade_set=None,
    *,
    stage: str,
) -> dict:
    """
    The `atomic_verify_failure_log.v(N).json` payload.

    Every atom that FAILS verification is logged with the six MCAL_PLAN 2 keys
    plus the doc/field it came from, and the false-negative audit is embedded so
    a reviewer reading the log sees the gating verdict next to the evidence for
    it.
    """
    entries: list[dict] = []
    for dv in verifications:
        for field, fv in dv.fields.items():
            grade = grade_set.get(dv.doc_id, field) if grade_set is not None else None
            human = grade.raw_grade if grade is not None else None
            for r in fv.failures():
                entries.append(
                    {
                        "doc_id": dv.doc_id,
                        "field": field,
                        "bucket": fv.bucket,
                        "claim_type": r.atom.claim_type,
                        "polarity": r.atom.polarity,
                        "tags": r.tags,
                        "competing_values": r.competing_values,
                        **r.log_entry(human),
                    }
                )

    audit = false_negative_audit(verifications, grade_set, stage=stage)
    total_atoms = sum(len(dv.all_results()) for dv in verifications)
    return {
        "version": settings.normalize_stage(stage),
        "n_docs": len(verifications),
        "n_atoms": total_atoms,
        "n_failures": len(entries),
        "failure_rate": round(len(entries) / total_atoms, 4) if total_atoms else None,
        "false_negative_audit": audit,
        "reason_code_counts": _count_reason_prefixes(entries),
        "failures": entries,
    }


def _count_reason_prefixes(entries: Sequence[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for e in entries:
        for reason in (e.get("failure_reason") or "").split("; "):
            key = reason.split(":", 1)[0].strip()
            if key:
                counts[key] = counts.get(key, 0) + 1
    return dict(sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])))


def save_failure_log(
    verifications: Sequence[DocumentVerification],
    grade_set=None,
    *,
    stage: str,
    draft: bool = True,
) -> Path:
    """Write `atomic_verify_failure_log.v(N).json`."""
    payload = build_failure_log(verifications, grade_set, stage=stage)
    return _write_json(
        settings.artifact_path("atomic_verify_failure_log.json", stage, draft=draft),
        payload,
    )


def load_failure_log(stage: str, *, draft: bool = False) -> dict:
    """Read a written failure log. Raises with an actionable message."""
    path = settings.artifact_path(
        "atomic_verify_failure_log.json", stage, draft=draft
    )
    if not path.exists():
        raise FileNotFoundError(
            f"No atomic-verify failure log for stage {stage}: {path}. It is "
            f"written by `python -m mcal.build --stage {stage}`; if you have not "
            f"run a build yet, {settings.ARTIFACTS_DIR} may not exist at all."
        )
    return json.loads(path.read_text(encoding="utf-8"))
