"""
Regression: LA Transit "Magnitude 7.5" vs the human's "Magnitude 7.0".

MCAL_PLAN 1(4) names this file explicitly, alongside the wildlife clause, and
prescribes the same cure for both: "Same decoupling as (3) for the magnitude ...
Fix: Atomic decomposition + coordination-splitting."

**That diagnosis does not survive contact with the document, and this file pins
the honest result rather than manufacturing a pass.**

What the document actually says (doc LA_TRANSIT = p1074_35556038322269):

  * p.146, verbatim: "The most severe ground shaking that would be felt in the
    starter line area would be generated by a Magnitude 7.5 earthquake occurring
    on the Newport-Inglewood Fault, giving Modified Mercalli Intensities of VII to
    IX (NOAA, 1973)."
  * p.144, Figure IV.4 ("Maximum Credible Earthquake Richter Magnitude", after
    Greensfelder 1974) lists Newport-Inglewood at 7.5.
  * p.145, prose: "Such correlations indicate that a Magnitude 7.0 is reasonable
    for the maximum credible event" on the Newport-Inglewood zone.
  * p.145 also: the San Andreas maximum credible event is "an event of Magnitude
    8.5".

So the document contains BOTH figures for the same fault under different framings,
and is internally inconsistent between its own table (7.5) and its own narrative
(7.0). The PRE-AMENDMENT summary wrote:

    "Seismic risks include strong shaking from the San Andreas (Magnitude 8.5
     maximum credible) and Newport-Inglewood (Magnitude 7.5) faults"

which carries "maximum credible" across the coordination onto a figure whose
framing on p.146 is a different one ("most severe ground shaking ... in the
starter line area"). Nothing is decoupled: 7.5 is genuinely attached to
Newport-Inglewood on two separate pages. The defect is a dropped/mislabeled
qualifier.

------------------------------------------------------------------------------
POST-RERUN STATUS (MCAL_PLAN build items #4/#5): THE PROSE DEFECT IS FIXED.
------------------------------------------------------------------------------
The plain-language + concreteness amendment changed this sentence to:

    "the maximum credible earthquake (the worst quake considered plausible) is
     Magnitude 8.5 on the San Andreas Fault and Magnitude 7.0-7.5 on the
     Newport-Inglewood Fault two miles from the Starter Line"

Three separate improvements, each asserted in `TestTheRangeIsAnImprovement`:

  * The bare wrong figure is GONE. There is no longer any "Magnitude 7.5"
    attributed to Newport-Inglewood; the string "Magnitude 7.5" does not occur in
    the subfield at all.
  * It reports a RANGE, 7.0-7.5, which spans exactly the document's own
    p.145-vs-p.144/146 contradiction. Both endpoints are documented. The summary
    stopped asserting one side of an internal inconsistency as fact.
  * "maximum credible earthquake" is GLOSSED in place ("the worst quake
    considered plausible") -- the plain-language clause working as intended -- and
    a geographic qualifier is attached ("two miles from the Starter Line") where
    the old prose had none.

This is the prevention side that `test_a_reviewer_is_still_required_for_this_class_of_error`
predicted would be needed, and it worked. The DETECTION side is unchanged: every
assertion in `TestSubstringVerificationCannotCatchIt`,
`TestScopeQualifierCatchesIt` and `TestTheLimitationThatRemains` still holds,
because they are about what the verifier can do with a 7.5 atom, and that is a
property of the document, not of this month's prose. The pre-amendment sentence is
still asserted against `segment_a/output/m2_pre_amendment/` so the before-state is
not lost.

One new friction the range introduces, pinned in
`TestTheRangeIsHarderToVerifyAtomically`: a range whose endpoints live on
DIFFERENT pages cannot be verified by a single-page atom citation, because
`require_numeric` checks the numbers against the one best-matching page. The
improved prose is therefore harder for the existing atom-level numeric check to
confirm than the wrong prose was. That is a real cost, not a bug.

Consequences of the underlying document situation, all still asserted below:

  1. The claim is SUBSTRING-TRUE. No substring verifier can reject it, including
     this one, including with `require_numeric=True`. `TestSubstringVerificationCannotCatchIt`.
  2. The scope-qualifier check IS what flags it: the atom as the summary phrases
     it (a bare fault attribute) drops the p.146 restriction, so
     `scope_qualifier_dropped` fires and the atom is tagged
     `T19_scope_qualifier_dropped`. `TestScopeQualifierCatchesIt`.
  3. The check flags the MISSING QUALIFIER, not the wrong number. Given the
     qualifier, the 7.5 atom correctly PASSES -- because with the qualifier it is
     true. No automated check in this module can adjudicate 7.0 vs 7.5, because
     the document asserts both. `TestTheLimitationThatRemains` states that
     explicitly so it stays visible instead of looking like a passing gate.
  4. Coordination splitting, the plan's prescribed fix, does not fire on this
     sentence at all -- pre- or post-amendment. `TestPlanPrescribedFixDoesNotApply`.

No LLM: atoms are constructed directly, mirroring what a decomposer would emit.
"""

from __future__ import annotations

import pytest

from mcal import atomic_verify as av
from mcal import quote_check as qc

from conftest import LA_TRANSIT

FIELD = "summary.environmental_impact"
SUBFIELD = "environmental_impact"

P144, P145, P146 = 144, 145, 146

QUOTE_P146 = (
    "The most severe ground shaking that would be felt in the starter line area "
    "would be generated by a Magnitude 7.5 earthquake occurring on the "
    "Newport-Inglewood Fault"
)
QUOTE_P145_70 = (
    "Such correlations indicate that a Magnitude 7.0 is reasonable for the "
    "maximum credible event."
)

# How the PRE-AMENDMENT summary phrased it: a bare fault attribute, with
# "maximum credible" carried over from the San Andreas item and no p.146
# restriction. Retained because every detection-side assertion in this file is
# about what the verifier does with THIS atom.
SUMMARY_ATOM_TEXT = (
    "The Newport-Inglewood Fault has a maximum credible Magnitude of 7.5."
)
# How it should have been phrased -- the p.146 claim, qualifier intact.
QUALIFIED_ATOM_TEXT = (
    "The most severe ground shaking felt in the starter line area would be "
    "generated by a Magnitude 7.5 earthquake on the Newport-Inglewood Fault."
)

# The post-amendment prose, verbatim (note the EN DASH in the range).
RANGE_PHRASE = "Magnitude 7.0\u20137.5 on the Newport-Inglewood Fault"
GLOSS_PHRASE = "maximum credible earthquake (the worst quake considered plausible)"
# The pre-amendment prose, verbatim.
PRE_AMENDMENT_PHRASE = (
    "San Andreas (Magnitude 8.5 maximum credible) and Newport-Inglewood "
    "(Magnitude 7.5)"
)


@pytest.fixture(scope="module")
def la(doc_loader):
    return doc_loader(LA_TRANSIT)


@pytest.fixture(scope="module")
def env_impact(m2_loader):
    m2 = m2_loader(LA_TRANSIT)
    value = (m2.get("summary") or {}).get(SUBFIELD)
    if not value:
        pytest.skip("no summary.environmental_impact in M2 output")
    return value


@pytest.fixture(scope="module")
def env_impact_pre_amendment(m2_pre_amendment_loader):
    m2 = m2_pre_amendment_loader(LA_TRANSIT)
    value = (m2.get("summary") or {}).get(SUBFIELD)
    if not value:
        pytest.skip("no summary.environmental_impact in the pre-amendment archive")
    return value


def _flat(value) -> str:
    return " ".join((value.get("text") or "").split())


def _page_text(doc, page):
    return next((p.text for p in doc.pages if p.page_num == page), "")


# --- The documentary facts this file's conclusions rest on ------------------


class TestDocumentaryFacts:
    """
    If any of these fail, the analysis above is wrong and every conclusion below
    must be re-derived. Cheap insurance against reasoning from a misremembered
    document.
    """

    def test_the_summary_no_longer_says_a_bare_7_5(self, env_impact):
        """
        Replaces `test_the_summary_still_says_7_5`, which asserted the DEFECT was
        present. It no longer is, so the assertion is inverted rather than
        relaxed: the subfield must still be about Newport-Inglewood, and must NOT
        contain a bare "Magnitude 7.5".

        old: "... and Newport-Inglewood (Magnitude 7.5) faults"
        new: "... and Magnitude 7.0-7.5 on the Newport-Inglewood Fault two miles
              from the Starter Line"
        """
        text = _flat(env_impact)
        assert "Newport-Inglewood" in text
        assert "Magnitude 7.5" not in text, (
            "the bare wrong figure is back; the MCAL_PLAN 3.14 plain-language / "
            "scope-qualifier clause has regressed"
        )
        assert RANGE_PHRASE in text

    def test_the_pre_amendment_summary_did_say_a_bare_7_5(
        self, env_impact_pre_amendment
    ):
        """
        History preserved. The defect this whole file was written about is
        asserted against the archive, not merely described in the docstring.
        """
        text = _flat(env_impact_pre_amendment)
        assert PRE_AMENDMENT_PHRASE in text
        assert "Magnitude 7.5" in text
        assert "7.0" not in text, (
            "the pre-amendment prose committed to 7.5 with no hint of the "
            "document's competing 7.0"
        )

    def test_p146_states_7_5_verbatim_for_newport_inglewood(self, la):
        page = " ".join(_page_text(la, P146).split())
        assert "Magnitude 7.5 earthquake occurring on the Newport-Inglewood" in page

    def test_p146_qualifies_it_as_most_severe_in_the_starter_line_area(self, la):
        page = " ".join(_page_text(la, P146).split())
        assert "most severe ground shaking that would be felt in the starter " \
               "line area" in page

    def test_p145_states_7_0_as_the_maximum_credible_event(self, la):
        page = " ".join(_page_text(la, P145).split())
        assert "Magnitude 7.0 is reasonable for the maximum credible event" in page

    def test_p144_table_also_lists_7_5(self, la):
        """
        The document contradicts itself: Figure IV.4's "Maximum Credible
        Earthquake Richter Magnitude" column gives Newport-Inglewood 7.5, while
        p.145's prose gives 7.0 for the same quantity.
        """
        page = _page_text(la, P144)
        assert "Maximum Credible" in page
        assert "Newport-" in page
        assert "7.5" in page

    def test_the_human_graded_it_wrong(self):
        from mcal import grades as grades_mod

        gs = grades_mod.load_grades()
        item = gs.get(LA_TRANSIT, FIELD)
        if item is None:
            pytest.skip("Evaluation sheet not available")
        assert not item.correct
        assert "7.5" in item.raw_grade or "Magnitude" in item.raw_grade

    def test_the_grade_now_describes_prose_that_no_longer_exists(
        self, env_impact, env_impact_pre_amendment
    ):
        """
        The caveat that applies to every label-conditioned statistic in the suite,
        stated on the one item where it is most visible: the human's grade for
        this (doc, field) is a complaint about "Magnitude 7.5", and the artifact
        on disk no longer says that. The grade is still recorded as WRONG, and
        this file does not re-grade it -- only a human can. Same finding as
        tests/test_atomic_verify.py::TestT01Invisibility's validity caveat.
        """
        assert "Magnitude 7.5" in _flat(env_impact_pre_amendment)
        assert "Magnitude 7.5" not in _flat(env_impact)


# --- The improvement --------------------------------------------------------


class TestTheRangeIsAnImprovement:
    """
    Pins the three things the amendment actually fixed, so that a future rerun
    that loses any of them fails here.

    This class asserts an IMPROVEMENT; it is not a relaxation of the old
    assertions. The old assertions are all still present, either unchanged
    (detection side) or re-pointed at the archive (prose side).
    """

    def test_it_reports_a_range_spanning_the_documents_own_contradiction(
        self, env_impact
    ):
        text = _flat(env_impact)
        assert RANGE_PHRASE in text
        # Both endpoints, and the low endpoint is the one the human wanted.
        assert "7.0" in text and "7.5" in text

    def test_both_endpoints_of_the_range_are_documented(self, la):
        """
        The range is not hedging -- it is accurate. 7.0 is p.145's narrative
        figure and 7.5 is p.144's table figure and p.146's ground-shaking figure,
        so the interval is exactly the span of the document's disagreement with
        itself. A summary that reports [7.0, 7.5] makes no claim the document does
        not support, which is what the bare 7.5 could not say.
        """
        p145 = " ".join(_page_text(la, P145).split())
        p146 = " ".join(_page_text(la, P146).split())
        assert "Magnitude 7.0" in p145
        assert "Magnitude 7.5" in p146
        assert "7.5" in _page_text(la, P144)
        window = " ".join(_page_text(la, p) for p in (P144, P145, P146))
        assert {"7.0", "7.5"} <= set(qc.numeric_tokens(window))

    def test_maximum_credible_earthquake_is_glossed_in_place(
        self, env_impact, env_impact_pre_amendment
    ):
        """
        MCAL_PLAN build item #4, the plain-language clause. The term whose
        mislabeling caused the original failure -- "maximum credible" carried onto
        the wrong figure -- is now defined for the reader at the point of use.
        """
        assert GLOSS_PHRASE in _flat(env_impact)
        assert GLOSS_PHRASE not in _flat(env_impact_pre_amendment)

    def test_a_geographic_qualifier_is_now_attached(self, env_impact):
        """
        The other half of the original defect was a dropped scope qualifier. The
        new prose carries one ("two miles from the Starter Line") where the old
        prose carried none.
        """
        text = _flat(env_impact)
        assert "two miles from the Starter Line" in text
        assert av.scope_cues(text)

    def test_the_san_andreas_half_is_still_correctly_attributed(self, env_impact):
        """Regression guard on the half that was always right."""
        assert "Magnitude 8.5 on the San Andreas Fault" in _flat(env_impact)


class TestTheRangeIsHarderToVerifyAtomically:
    """
    The cost of the improvement, measured. Neither hidden nor treated as a bug.

    "Magnitude 7.0-7.5 on the Newport-Inglewood Fault" is a single claim whose two
    numbers live on two different pages (7.0 on p.145, 7.5 on p.144/146).
    `check_quote` picks ONE best-matching page and runs `require_numeric` against
    that page's text, so whichever page wins, the other endpoint is reported
    missing and the verdict caps at "mixed" -- never "no", but never "yes" either.

    Consequence for MCAL_PLAN 3.4: an atom carrying a cross-page range needs
    either a multi-page evidence window or to be decomposed into one atom per
    endpoint. Recorded here so that when range-valued atoms start showing up in
    the failure log as `numeric` downgrades, the cause is already written down.
    """

    def test_the_range_claim_caps_at_mixed_on_every_cited_page(self, la):
        for pages in ([P144], [P145], [P146], [P144, P145, P146]):
            r = qc.check_quote(RANGE_PHRASE, pages, la, require_numeric=True)
            assert r.quote_numbers == ["7.0", "7.5"]
            assert r.verified == "mixed", pages
            assert r.missing_numbers, pages
            # The PROSE is fully present; only one figure is unconfirmed.
            assert r.coverage == 1.0, pages

    def test_widening_the_page_list_does_not_help(self, la):
        """
        Because the numeric check is per-matched-page, not per-window. Adding
        pages changes WHICH page matches, not how many are checked.
        """
        narrow = qc.check_quote(RANGE_PHRASE, [P145], la, require_numeric=True)
        wide = qc.check_quote(
            RANGE_PHRASE, [P144, P145, P146], la, require_numeric=True
        )
        assert narrow.missing_numbers == wide.missing_numbers

    def test_split_into_one_atom_per_endpoint_both_verify(self, la):
        """
        The available remedy, demonstrated. Decomposing the range into its two
        endpoint claims and citing each to its own page verifies both -- which is
        the atomic-decomposition argument arriving from a new direction.
        """
        r75 = qc.check_quote(
            "a Magnitude 7.5 earthquake occurring on the Newport-Inglewood Fault",
            [P146], la, require_numeric=True,
        )
        r70 = qc.check_quote(QUOTE_P145_70, [P145], la, require_numeric=True)
        assert r75.verified == "yes" and r75.missing_numbers == []
        assert r70.verified == "yes" and r70.missing_numbers == []



# --- (1) Substring verification cannot catch it -----------------------------


class TestSubstringVerificationCannotCatchIt:
    def test_the_wrong_figure_verifies_against_its_cited_page(self, la):
        """
        The plan's prescribed mechanism, applied faithfully, ACCEPTS this claim.
        That is the finding, not a bug in the verifier.
        """
        r = qc.check_quote(QUOTE_P146, [P146], la, require_numeric=True)
        assert r.verified == "yes"
        assert r.numeric_ok is True
        assert r.missing_numbers == []

    def test_numeric_channel_is_working_correctly(self, la):
        """
        The numeric channel is not failing to distinguish the figures -- it
        distinguishes them fine. 7.5 is simply the one on the page.
        """
        swapped = QUOTE_P146.replace("7.5", "7.0")
        r = qc.check_quote(swapped, [P146], la, require_numeric=True)
        assert r.missing_numbers == ["7.0"]
        assert r.verified == "mixed"

    def test_atom_level_substring_and_numeric_checks_both_accept_it(self, la):
        """
        Same result one level up. As a `numeric` atom with the p.146 quote, the
        MCAL_PLAN 3.4 step-2 checks -- OCR-normalized substring match plus
        `require_numeric` value agreement -- both pass. Whatever rejects this
        claim, it is not those.
        """
        atom = av.Atom(
            id="mag",
            text="A Magnitude 7.5 earthquake could occur on the "
                 "Newport-Inglewood Fault.",
            subject="the Newport-Inglewood Fault",
            predicate="could generate an earthquake of magnitude",
            object="7.5",
            page=P146,
            evidence_quote=QUOTE_P146,
            claim_type="numeric",
            polarity="affirmative",
            coreference_resolved=True,
            field=FIELD,
        )
        r = av.verify_atom(atom, la)
        assert r.check is not None
        assert r.check.verified == "yes"
        assert r.check.numeric_ok is True
        assert r.check.missing_numbers == []
        # Every reason that remains is the qualifier deviation, nothing else.
        assert r.reasons
        assert all(p.startswith("scope_qualifier") for p in r.reasons)

    def test_both_figures_are_present_in_the_cited_window(self, la):
        """
        Root cause, stated as a measurement: 7.0 and 7.5 are BOTH in the
        document, so no amount of substring precision can pick between them.
        """
        r70 = qc.check_quote(QUOTE_P145_70, [P145], la, require_numeric=True)
        assert r70.verified == "yes"
        assert r70.numeric_ok is True
        window = " ".join(_page_text(la, p) for p in (P144, P145, P146))
        nums = set(qc.numeric_tokens(window))
        assert {"7.5", "7.0"} <= nums


# --- (2) The scope-qualifier check is what flags it -------------------------


class TestScopeQualifierCatchesIt:
    def _summary_atom(self):
        """The atom as the summary's phrasing yields it: no qualifier."""
        return av.Atom(
            id="mag_summary",
            text=SUMMARY_ATOM_TEXT,
            subject="the Newport-Inglewood Fault",
            predicate="has a maximum credible magnitude of",
            object="7.5",
            page=P146,
            evidence_quote=QUOTE_P146,
            claim_type="numeric",
            polarity="affirmative",
            coreference_resolved=True,
            scope_qualifier=None,
            field=FIELD,
        )

    def test_flagged_and_tagged_t19(self, la):
        r = av.verify_atom(self._summary_atom(), la)
        assert r.status == av.STATUS_FAIL
        assert "T19_scope_qualifier_dropped" in r.tags

    def test_the_reason_names_the_dropped_qualifier(self, la):
        r = av.verify_atom(self._summary_atom(), la)
        dropped = " ".join(r.dropped_qualifiers).lower()
        assert "most severe" in dropped
        assert "starter line area" in dropped

    def test_the_qualifier_is_detected_on_the_source_page(self, la):
        names = {
            n for n, _p in av.page_qualifiers(" ".join(_page_text(la, P146).split()))
        }
        assert "superlative_scope" in names
        assert "geographic_scope" in names

    def test_it_is_the_qualifier_check_and_nothing_else(self, la):
        """
        Isolation. Every reason on this atom is a qualifier reason, and the quote
        and numeric channels both pass. Without the deviation described in
        atomic_verify.py's docstring, this atom would pass.

        Two reasons fire, both T19 and both correct: `scope_qualifier_missing`
        because the atom text carries a superlative ("maximum credible") with no
        qualifier, and `scope_qualifier_dropped` because the source sentence's
        restriction is not reproduced.
        """
        r = av.verify_atom(self._summary_atom(), la)
        assert r.reasons
        assert all(p.startswith("scope_qualifier") for p in r.reasons)
        assert {p.split(":", 1)[0] for p in r.reasons} == {
            "scope_qualifier_missing", "scope_qualifier_dropped",
        }
        assert r.tags == ["T19_scope_qualifier_dropped"]
        assert r.check is not None and r.check.verified == "yes"
        assert r.check.numeric_ok is True

    def test_t19_is_a_real_taxonomy_code(self):
        from mcal import taxonomy

        tax = taxonomy.seed_taxonomy("v1", include_proposed=True)
        tag = tax.by_name("T19_scope_qualifier_dropped")
        assert tag is not None
        assert "summary.*" in tag.applies_to

    def test_end_to_end_subfield_reports_t19(self, la, env_impact):
        payload = [
            {
                "text": SUMMARY_ATOM_TEXT,
                "subject": "the Newport-Inglewood Fault",
                "predicate": "has a maximum credible magnitude of",
                "object": "7.5",
                "page": P146,
                "evidence_quote": QUOTE_P146,
                "claim_type": "numeric",
                "polarity": "affirmative",
                "coreference_resolved": True,
                "scope_qualifier": None,
            }
        ]
        fv = av.verify_subfield(
            LA_TRANSIT, FIELD, env_impact, la,
            call=lambda s, u, **kw: {"atoms": payload},
        )
        assert fv.n_failed == 1
        assert "T19_scope_qualifier_dropped" in fv.tags
        # numeric failure -> 2x penalty, single atom, so the score floors at 0.
        assert fv.score == 0.0


# --- (3) The limitation that remains ---------------------------------------


class TestTheLimitationThatRemains:
    """
    Stated as assertions so the boundary of what is verified cannot quietly
    expand. These are NOT aspirational; they pin behaviour that will not change
    without a design change.
    """

    def test_the_qualified_claim_correctly_passes(self, la):
        """
        The check flags a MISSING QUALIFIER, not a wrong number. Carry the p.146
        restriction and the 7.5 claim is true, so it must pass. A verifier that
        rejected this would be rejecting a correct sentence.
        """
        atom = av.Atom(
            id="mag_qualified",
            text=QUALIFIED_ATOM_TEXT,
            page=P146,
            evidence_quote=QUOTE_P146,
            claim_type="comparative",
            scope_qualifier="that would be felt in the starter line area",
            field=FIELD,
        )
        r = av.verify_atom(atom, la)
        assert r.status == av.STATUS_PASS, r.reasons
        assert r.dropped_qualifiers == []

    def test_the_verifier_cannot_choose_between_7_0_and_7_5(self, la):
        """
        THE LIMITATION. Both figures verify against their own cited pages with
        their own qualifiers intact. Deciding which one belongs in a one-sentence
        summary of seismic risk requires knowing that p.145's narrative supersedes
        p.144's table -- a judgement about the document's internal inconsistency
        that no substring or qualifier check performs. The human made that
        judgement; the machine cannot.
        """
        atom_75 = av.Atom(
            id="a75", text=QUALIFIED_ATOM_TEXT, page=P146,
            evidence_quote=QUOTE_P146, claim_type="comparative",
            scope_qualifier="that would be felt in the starter line area",
        )
        atom_70 = av.Atom(
            id="a70",
            text="A Magnitude 7.0 is reasonable for the maximum credible event "
                 "on the Newport-Inglewood zone.",
            page=P145,
            evidence_quote=QUOTE_P145_70,
            claim_type="comparative",
            scope_qualifier="the maximum credible event",
        )
        r75 = av.verify_atom(atom_75, la)
        r70 = av.verify_atom(atom_70, la)
        assert r75.status == av.STATUS_PASS
        assert r70.status == av.STATUS_PASS
        assert r75.status == r70.status, (
            "both are supported by the document, so the verifier is indifferent "
            "between them. This is the documented limitation, not a bug."
        )

    def test_the_contradiction_is_surfaced_but_not_adjudicated(self, la):
        """
        `competing_values` is the only signal that shows a reviewer there is
        another figure in play. It is advisory: it reports 7.0 (and other
        magnitudes) alongside the 7.5 claim, and changes no verdict. Gating on it
        is not viable -- on the OCR'd cost tables in this same document a numeric
        atom has dozens of "competitors" and nearly all are spurious.
        """
        atom = av.Atom(
            id="mag", text=QUALIFIED_ATOM_TEXT, page=P145,
            evidence_quote=QUOTE_P145_70.replace("7.0", "7.5"),
            claim_type="comparative",
            scope_qualifier="the maximum credible event",
        )
        r = av.verify_atom(atom, la)
        assert "7.0" in r.competing_values
        # Advisory: it did not by itself force a failure.
        assert not any("competing" in reason for reason in r.reasons)

    def test_a_reviewer_is_still_required_for_this_class_of_error(self, la):
        """
        The honest summary of this file. `T19` says "a qualifier was dropped", not
        "the figure is wrong". A summary that keeps its qualifier and still picks
        the table value over the narrative value passes every automated check in
        this module. MCAL_PLAN 3.14's plain-language clause and the Critic's
        rubric Q10 are the prevention side; the reviewer is the detection side.

        Post-rerun note: the PREVENTION side landed and worked on this very item
        (`TestTheRangeIsAnImprovement`) -- the amended prompt produced a range
        instead of the bare wrong figure. That does not change the assertion
        below. The verifier's indifference is a property of the document, and a
        future extraction that reverts to a bare qualified 7.5 would still sail
        through. Prevention is not detection, and this test is the reminder.
        """
        atom = av.Atom(
            id="still_wrong_but_qualified",
            text=QUALIFIED_ATOM_TEXT,
            page=P146,
            evidence_quote=QUOTE_P146,
            claim_type="comparative",
            scope_qualifier="that would be felt in the starter line area",
        )
        assert av.verify_atom(atom, la).ok is True


# --- (4) The plan's prescribed fix does not apply ---------------------------


class TestPlanPrescribedFixDoesNotApply:
    # The pre-amendment sentence.
    SENTENCE = (
        "Seismic risks include strong shaking from the San Andreas (Magnitude "
        "8.5 maximum credible) and Newport-Inglewood (Magnitude 7.5) faults, "
        "with potential liquefaction and oil/gas/hydrogen sulphide seeps near "
        "the La Brea Tar Pits."
    )
    # The post-amendment sentence that replaced it, verbatim.
    SENTENCE_POST_AMENDMENT = (
        "Deep bored subway tunnels are judged safer in earthquakes than surface "
        "or aerial structures \u2014 the maximum credible earthquake (the worst "
        "quake considered plausible) is Magnitude 8.5 on the San Andreas Fault "
        "and Magnitude 7.0\u20137.5 on the Newport-Inglewood Fault two miles "
        "from the Starter Line, and 22,000 pre-1933 substandard brick buildings "
        "could drop debris on aerial structures."
    )

    def test_coordination_splitting_does_not_fire(self):
        """
        MCAL_PLAN 1(4) prescribes "atomic decomposition + coordination-splitting"
        for this case. The coordination here is inside a prepositional object
        ("from the San Andreas ... and Newport-Inglewood ... faults"), not a
        coordinated subject list, so the deterministic splitter correctly declines
        it. The plan's mechanism is simply not the one that applies.

        Unchanged by the rerun, and asserted on BOTH sentences: the amended
        version coordinates two fault-and-magnitude pairs inside a predicate and
        then joins a second independent clause, so it is declined for two
        independent reasons instead of one.
        """
        assert av.coordinated_claims(self.SENTENCE) == []
        assert av.coordinated_claims(self.SENTENCE_POST_AMENDMENT) == []

    def test_the_pre_amendment_sentence_is_in_the_archive(
        self, env_impact_pre_amendment
    ):
        """
        Replaces the old `test_the_sentence_is_in_the_m2_output`. The sentence it
        pinned is no longer in `segment_a/output/m2/`, so the assertion moves to
        the corpus where it is true rather than being deleted.
        """
        assert PRE_AMENDMENT_PHRASE in _flat(env_impact_pre_amendment)

    def test_the_post_amendment_sentence_is_in_the_m2_output(self, env_impact):
        """
        And the sentence that replaced it is pinned in the live output, so this
        class is still measuring the splitter against real prose rather than a
        hand-typed string.
        """
        text = _flat(env_impact)
        assert self.SENTENCE_POST_AMENDMENT in text
        assert PRE_AMENDMENT_PHRASE not in text

    def test_the_san_andreas_half_is_correct(self, la):
        """
        Which is why the coordination reads as parallel and the error was easy to
        miss: 8.5 IS the San Andreas maximum credible event on p.145. Only the
        second half of the pre-amendment coordination carried a mislabeled
        framing.
        """
        r = qc.check_quote(
            "the maximum credible earthquake on the San Andreas Fault as an "
            "event of Magnitude 8.5",
            [P145],
            la,
            require_numeric=True,
        )
        assert r.verified == "yes"
        assert r.numeric_ok is True
